# O N E  P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#PlayerOne
[SingP1Static]
Inherits = SingDefaultAvatarFrame
Color = P1Dark

[SingP1Text]
Inherits = SingDefaultPlayerText

[SingP1Static2]
Inherits = SingDefaultScoreBG
Color = P1Dark

[SingP1TextScore]
Inherits = SingDefaultPlayerTextScore

[SingP1SingBar]
Inherits = SingDefaultSingBar

[SingP1Avatar]
Inherits = SingDefaultAvatar

