# T W O  P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1TwoPStatic]
Inherits = SingDefaultAvatarFrame
Y = 95
Color = P1Dark

[SingP1TwoPText]
Inherits = SingDefaultPlayerText
Y = 122

[SingP1TwoPStatic2]
Inherits = SingDefaultScoreBG
Y = 102
Color = P1Dark

[SingP1TwoPTextScore]
Inherits = SingDefaultPlayerTextScore
Y = 104

[SingP1TwoPSingBar]
Inherits = SingDefaultSingBar
Y = 136

[SingP1TwoPAvatar]
Inherits = SingDefaultAvatar
Y = 99

#Player Two
[SingP2RStatic]
Inherits = SingDefaultAvatarFrame
Y = 275
Color = P2Dark

[SingP2RText]
Inherits = SingDefaultPlayerText
Y = 302

[SingP2RStatic2]
Inherits = SingDefaultScoreBG
Y = 282
Color = P2Dark

[SingP2RTextScore]
Inherits = SingDefaultPlayerTextScore
Y = 284

[SingP2RSingBar]
Inherits = SingDefaultSingBar
Y = 316

[SingP2RAvatar]
Inherits = SingDefaultAvatar
Y = 280

