# T H R E E  P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1ThreePStatic]
Inherits = SingDefaultAvatarFrame
X = 16
Y = 57
Color = P1Dark

[SingP1ThreePStatic2]
Inherits = SingDefaultScoreBG
X = 75
Y = 61
Color = P1Dark

[SingP1ThreePTextScore]
Inherits = SingDefaultPlayerTextScore
X = 93
Y = 63

[SingP1ThreePSingBar]
Inherits = SingDefaultSingBar
X = 75
Y = 95

[SingP1ThreePAvatar]
Inherits = SingDefaultAvatar
X = 20
Y = 62

#Player Two
[SingP2MStatic]
Inherits = SingP1ThreePStatic
X = 311
Color = P2Dark

[SingP2MStatic2]
Inherits = SingP1ThreePStatic2
X = 370
Color = P2Dark

[SingP2MTextScore]
Inherits = SingP1ThreePTextScore
X = 388

[SingP2MSingBar]
Inherits = SingP1ThreePSingBar
X = 370

[SingP2MAvatar]
Inherits = SingP1ThreePAvatar
X = 315

#Player Three
[SingP3RStatic]
Inherits = SingP1ThreePStatic
X = 611
Color = P3Dark

[SingP3RStatic2]
Inherits = SingP1ThreePStatic2
X = 670
Color = P3Dark

[SingP3RTextScore]
Inherits = SingP1ThreePTextScore
X = 688

[SingP3SingBar]
Inherits = SingP1ThreePSingBar
X = 670

[SingP3RAvatar]
Inherits = SingP1ThreePAvatar
X = 615

