[ScoreBackground]
Tex = ScoreScreenBG

[ScoreText1]
X = 70
Y = 6
Color = White
Font = 0
Style = 0
Size = 60
Text = SONG_SCORE
Align = 0

[ScoreTextArtistTitle]
X = 70
Y = 59
Color = White
Font = 0
Style = 0
Size = 30
Align = 0
Text = ArtistTitle

[ScoreStatic1]
Inherits = DefaultIcon
Tex = ScoreIcon

[ScoreStatic2]
Inherits = DefaultBar1

[ScoreStatic3]
Inherits = DefaultBar2

[ScoreStatic4]
Inherits = DefaultLegendStatic
Tex = ButtonEnter

[ScoreText2]
Inherits = DefaultLegendText
Text = SING_LEGEND_CONTINUE

[ScoreText3]
Inherits = DefaultTextWhereAmI
Text = SONG_SCORE_WHEREAMI

#end of main stuff

