# # # # # # # # # # # # # # # # # # One Player Score # # # # # # # # # # # #
[ScoreTextName1]
X = 197
Y = 280
Font = 0
Style = 1
Size = 40
Text = P1
Color = White
Align = 0

# Rating
[ScoreStaticRatingPicture1]
X = 385
Y = 165
H = 75
W = 75

[ScoreTextScore1]
X = 422
Y = 235
W = 100
Color = White
Font = 0
Style = 0
Size = 27
Text = Tone Deaf
Align = 1

# Note Score
[ScoreStaticBoxDark1]
Tex = ScoreBar_box_dark
X = 200
Y = 327
W = 22
H = 20
Color = P1Dark
Type = Colorized

[ScoreTextNotes1]
X = 227
Y = 322
Color = White
Font = 0
Style = 0
Size = 30
Text = SING_NOTES
Align = 0

[ScoreTextNotesScore1]
X = 487
Y = 322
Color = White
Font = 0
Style = 0
Size = 30
Align = 2
Text = 0

# A simple line
[ScorePlayer1Static1]
Tex = ScoreLine
X = 200
Y = 351
W = 287
H = 1
Color = White
Type = Colorized

# Line Bonus
[ScoreStaticBoxLight1]
Inherits = ScoreStaticBoxDark1
Tex = ScoreBar_box_light
Y = 358
Color = P1Light

[ScoreTextLineBonus1]
Inherits = ScoreTextNotes1
Y = 352
Text = SING_PHRASE_BONUS

[ScoreTextLineBonusScore1]
Inherits = ScoreTextNotesScore1
Y = 352

# A simple line
[ScorePlayer1Static2]
Inherits = ScorePlayer1Static1
Y = 382

# Golden Notes
[ScoreStaticBoxLightest1]
Inherits = ScoreStaticBoxDark1
Tex = ScoreBar_box_lightest
Y = 390
Color = P1Lightest

[ScoreTextGoldenNotes1]
Inherits = ScoreTextNotes1
Y = 383
Text = SING_GOLDEN_NOTES

[ScoreTextGoldenNotesScore1]
Inherits = ScoreTextNotesScore1
Y = 383

[ScoreTextTotal1]
X = 237
Y = 454
Color = White
Font = 0
Style = 0
Size = 30
Text = SING_TOTAL
Align = 0
Reflection = 1
ReflectionSpacing = 26

[ScoreTextTotalSCore1]
X = 487
Y = 444
Color = White
Font = 0
Style = 0
Size = 42
Align = 2
Text = 0
Reflection = 1
ReflectionSpacing = 24

#ScoreBar
[ScoreStaticBackLevel1]
Tex = ScoreLevel
X = 503
Y = 168
W = 95
H = 310
Color = P1Lightest
Type = Colorized

[ScoreStaticBackLevelRound1]
Tex = ScoreLevelRound
X = 503
Y = 138
W = 95
H = 8
Color = P1Lightest
Type = Colorized

[ScoreStaticLevel1]
Tex = ScoreLevel
X = 503
Y = 400
W = 95
H = 10
Color = P1Dark
Type = Colorized

[ScoreStaticLevelRound1]
Tex = ScoreLevelRound
X = 503
Y = 392
W = 95
H = 8
Color = P1Dark
Type = Colorized

[ScorePlayer1Static3]
Tex = ScoreEndCap
X = 499
Y = 478
W = 110
H = 30
z = 0.9
Color = P1Dark
Type = Colorized
Reflection = 1
ReflectionSpacing = 0

[ScorePlayer1Static4]
Tex = ScoreGlassBox
X = 499
Y = 148
W = 113
H = 331
z = 0.89
Color = White
Type = Transparent

[ScorePlayer1Static5]
Tex = P
X = 200
Y = 455
W = 26
H = 23
Color = P1Dark
Type = Colorized
Reflection = 1
ReflectionSpacing = 31

[ScorePlayer1Text1]
Text = P1
X = 204
Y = 458
Size = 18
Font = 0
Style = 1
Color = White
Type = Colorized
Reflection = 1
ReflectionSpacing = 40

[ScorePlayer1Avatar]
X = 203
Y = 168
W = 104
H = 104
Z = 1

[ScorePlayer1Static6]
X = 195
Y = 160
W = 120
H = 120
Z = 0.9
Tex = AvatarFrame2
Color = P1Dark
Type = Transparent

