# # # # # # # # # # # # # # # # # # Two Player Score # # # # # # # # # # # #
# P L A Y E R   O N E
[ScoreTextName2]
X = 42
Y = 284
Font = 0
Style = 1
Size = 36
Text = P1
Color = White
Align = 0

[ScoreStaticRatingPicture2]
X = 180
Y = 165
H = 75
W = 75

[ScoreTextScore2]
X = 217
Y = 235
W = 100
Color = White
Font = 0
Style = 0
Size = 27
Text = Tone Deaf
Align = 1

[ScoreStaticBoxDark2]
Tex = ScoreBar_box_dark
X = 45
Y = 327
W = 22
H = 20
Color = P1Dark
Type = Colorized

[ScoreTextNotes2]
X = 72
Y = 324
Color = White
Font = 0
Style = 0
Size = 24
Text = SING_NOTES
Align = 0

[ScoreTextNotesScore2]
X = 282
Y = 324
Color = White
Font = 0
Style = 0
Size = 24
Align = 2
Text = 0000

[ScoreStaticBoxLight2]
Inherits = ScoreStaticBoxDark2
Tex = ScoreBar_box_light
Y = 358
Color = P1Lightest

[ScoreTextLineBonus2]
Inherits = ScoreTextNotes2
Y = 355
Text = SING_PHRASE_BONUS

[ScoreTextLineBonusScore2]
Inherits = ScoreTextNotesScore2
Y = 355

[ScoreStaticBoxLightest2]
Inherits = ScoreStaticBoxLight2
Tex = ScoreBar_box_lightest
Y = 390
Color = P1Lightest

[ScoreTextGoldenNotes2]
Inherits = ScoreTextNotes2
Y = 387
Text = SING_GOLDEN_NOTES

[ScoreTextGoldenNotesScore2]
Inherits = ScoreTextNotesScore2
Y = 387

[ScoreTextTotal2]
X = 82
Y = 454
Color = White
Font = 0
Style = 0
Size = 30
Text = SING_TOTAL
Reflection = 1
ReflectionSpacing = 24

[ScoreTextTotalSCore2]
X = 283
Y = 444
Color = White
Font = 0
Style = 0
Size = 42
Align = 2
Text = 00000
Reflection = 1
ReflectionSpacing = 24

# Lines
[ScorePlayer2Static1]
Tex = ScoreLine
X = 45
Y = 351
W = 237
H = 1
Type = Colorized
Color = White

[ScorePlayer2Static2]
Inherits = ScorePlayer2Static1
Y = 382

#ScoreBar
[ScoreStaticBackLevel2]
Tex = ScoreLevel
X = 298
Y = 168
W = 95
H = 310
Color = P1Lightest
Type = Colorized

[ScoreStaticBackLevelRound2]
Tex = ScoreLevelRound
X = 298
Y = 138
W = 95
H = 8
Color = P1Lightest
Type = Colorized

[ScoreStaticLevel2]
Tex = ScoreLevel
X = 298
Y = 400
W = 95
H = 10
Color = P1Dark
Type = Colorized

[ScoreStaticLevelRound2]
Tex = ScoreLevelRound
X = 298
Y = 392
W = 95
H = 8
Color = P1Dark
Type = Colorized

[ScorePlayer2Static3]
Tex = ScoreEndCap
X = 294
Y = 478
W = 110
H = 30
z = 0.9
Color = P1Dark
Type = Colorized
Reflection = 1
ReflectionSpacing = 0

[ScorePlayer2Static4]
Tex = ScoreGlassBox
X = 294
Y = 148
W = 113
H = 331
z = 0.89
Color = White
Type = Transparent
 
[ScorePlayer2Static5]
Tex = P
X = 45
Y = 455
W = 26
H = 23
Type = Colorized
Color = P1Dark
Reflection = 1
ReflectionSpacing = 31

[ScorePlayer2Text1]
Text = P1
X = 49
Y = 458
Size = 18
Font = 0
Style = 1
Color = White
Type = Colorized
Reflection = 1
ReflectionSpacing = 40

[ScorePlayer2Avatar]
X = 48
Y = 168
W = 104
H = 104
Z = 1

[ScorePlayer2Static6]
X = 40
Y = 160
W = 120
H = 120
Z = 0.9
Tex = AvatarFrame2
Color = P1Dark
Type = Transparent

# P L A Y E R   T W O (mirrors player 1)
[ScoreTextName3]
Inherits = ScoreTextName2
X = 755
Align = 2

[ScoreStaticRatingPicture3]
Inherits = ScoreStaticRatingPicture2
X = 545

[ScoreTextScore3]
Inherits = ScoreTextScore2
X = 583

[ScoreStaticBoxDark3]
Inherits = ScoreStaticBoxDark2
X = 733
Color = P2Dark

[ScoreTextNotes3]
Inherits = ScoreTextNotes2
X = 728
Align = 2

[ScoreTextNotesScore3]
Inherits = ScoreTextNotesScore2
X = 518
Align = 0

[ScoreStaticBoxLight3]
Inherits = ScoreStaticBoxLight2
X = 733
Color = P2Lightest

[ScoreTextLineBonus3]
Inherits = ScoreTextLineBonus2
X = 728
Align = 2

[ScoreTextLineBonusScore3]
Inherits = ScoreTextLineBonusScore2
X = 518
Align = 0

[ScoreStaticBoxLightest3]
Inherits = ScoreStaticBoxLightest2
X = 733
Color = P2Lightest

[ScoreTextGoldenNotes3]
Inherits = ScoreTextGoldenNotes2
X = 728
Align = 2

[ScoreTextGoldenNotesScore3]
Inherits = ScoreTextGoldenNotesScore2
X = 518
Align = 0

[ScoreTextTotal3]
Inherits = ScoreTextTotal2
X = 718
Align = 2

[ScoreTextTotalScore3]
Inherits = ScoreTextTotalSCore2
X = 517
Align = 0

#Lines
[ScorePlayer3Static1]
Inherits = ScorePlayer2Static1
X = 518

[ScorePlayer3Static2]
Inherits = ScorePlayer2Static2
Tex = ScoreLine
X = 518

#ScoreBar
[ScoreStaticBackLevel3]
Inherits = ScoreStaticBackLevel2
X = 409
Color = P2Lightest

[ScoreStaticBackLevelRound3]
Inherits = ScoreStaticBackLevelRound2
X = 409
Color = P2Lightest

[ScoreStaticLevel3]
Inherits = ScoreStaticLevel2
X = 409
Color = P2Dark

[ScoreStaticLevelRound3]
Inherits = ScoreStaticLevelRound2
X = 409
Color = P2Dark

[ScorePlayer3Static3]
Inherits = ScorePlayer2Static3
X = 405
Color = P2Dark

[ScorePlayer3Static4]
Inherits = ScorePlayer2Static4
X = 405

[ScorePlayer3Static5]
Inherits = ScorePlayer2Static5
X = 729
Color = P2Dark

[ScorePlayer3Text1]
Inherits = ScorePlayer2Text1
Text = P2
X = 733

[ScorePlayer3Avatar]
Inherits = ScorePlayer2Avatar
X = 648

[ScorePlayer3Static6]
Inherits = ScorePlayer2Static6
X = 640
Color = P2Dark

