# # # # # # # # # # # # # # # # # # Three Player Score # # # # # # # # # # # #
# P L A Y E R  O N E
[ScoreTextName4]
X = 20
Y = 135
Font = 0
Style = 1
Size = 38
Align = 0
Text = P1
Color = White

# Rating
[ScoreStaticRatingPicture4]
X = 160
Y = 265
H = 75
W = 75
Z = 2

[ScoreTextScore4]
X = 197
Y = 335
W = 100
Color = White
Font = 0
Style = 0
Size = 27
Text = Tone Deaf
Align = 1

[ScoreTextNotes4]
X = 45
Y = 180
Font = 0
Style = 0
Size = 26
Align = 0
Text = SING_NOTES
Color = White

[ScoreTextNotesScore4]
X = 260
Y = 180
Font = 0
Style = 0
Size = 26
Align = 2
Text = 0000
Color = White

[ScoreTextLineBonus4]
Inherits = ScoreTextNotes4
Y = 205
Text = SING_PHRASE_BONUS

[ScoreTextLineBonusScore4]
Inherits = ScoreTextNotesScore4
Y = 205

[ScoreTextGoldenNotes4]
Inherits = ScoreTextNotes4
Y = 230
Text = SING_GOLDEN_NOTES

[ScoreTextGoldenNotesScore4]
Inherits = ScoreTextNotesScore4
Y = 230

[ScoreStaticBoxDark4]
Tex = ScoreBar_box_dark
X = 20
Y = 185
W = 22
H = 20
Color = P1Dark
Type = Colorized

[ScoreStaticBoxLight4]
Inherits = ScoreStaticBoxDark4
Tex = ScoreBar_box_light
Y = 210
Color = P1Light

[ScoreStaticBoxLightest4]
Inherits = ScoreStaticBoxDark4
Tex = ScoreBar_box_lightest
Y = 235
Color = P1Lightest

[ScoreTextTotal4]
X = 55
Y = 500
Font = 0
Style = 0
Size = 30
Align = 0
Text = SING_TOTAL
Color = White

[ScoreTextTotalScore4]
X = 250
Y = 495
Font = 0
Style = 0
Size = 42
Align = 2
Text = 00000
Color = White

#lines
[ScorePlayer4Static1]
X = 20
Y = 180
W = 240
H = 1
Tex = ScoreLine
Type = Colorized
Color = White

[ScorePlayer4Static2]
Inherits = ScorePlayer4Static1
Y = 205

[ScorePlayer4Static3]
Inherits = ScorePlayer4Static1
Y = 230

[ScorePlayer4Static4]
Inherits = ScorePlayer4Static1
Y = 255

#ScoreBar
[ScoreStaticBackLevel4]
Tex = ScoreLevel
X = 24
Y = 291
W = 95
H = 169
Color = P4Lightest
Type = Colorized

[ScoreStaticBackLevelRound4]
Tex = ScoreLevelRound
X = 24
Y = 138
W = 95
H = 8
Color = P4Lightest
Type = Colorized

[ScoreStaticLevel4]
Tex = ScoreLevel
X = 24
Y = 400
W = 95
H = 10
Color = P4Dark
Type = Colorized

[ScoreStaticLevelRound4]
Tex = ScoreLevelRound
X = 24
Y = 392
W = 95
H = 8
Color = P4Dark
Type = Colorized

[ScorePlayer4Static5]
Tex = ScoreEndCap
X = 20
Y = 450
W = 110
H = 30
Z = 0.9
Color = P1Dark
Type = Colorized
Reflection = 1
ReflectionSpacing = 0

[ScorePlayer4Static6]
Tex = ScoreGlassBox
X = 20
Y = 270
W = 113
H = 180
Z = 0.89
Color = White
Type = Transparent

[ScorePlayer4Static7]
Tex = P
X = 20
Y = 500
W = 25
H = 25
Type = Colorized
Color = P1Dark
Z = 0.9
Reflection = 1
ReflectionSpacing = 4

[ScorePlayer4Text1]
Text = P1
X = 24
Y = 503
Size = 18
Font = 0
Style = 1
Type = Colorized
Color = White
Z = 1
Reflection = 1
ReflectionSpacing = 16

[ScorePlayer4Avatar]
X = 157
Y = 390
W = 84
H = 84
Z = 1

[ScorePlayer4Static8]
X = 149
Y = 382
W = 100
H = 100
Z = 0.9
Tex = AvatarFrame2
Color = P1Dark
Type = Transparent

# P L A Y E R  T W O (Mirrors player 1)
[ScoreTextName5]
Inherits = ScoreTextName4
X = 280
Text = P2

# Rating
[ScoreStaticRatingPicture5]
Inherits = ScoreStaticRatingPicture4
X = 420

[ScoreTextScore5]
Inherits = ScoreTextScore4
X = 457

[ScoreTextNotes5]
Inherits = ScoreTextNotes4
X = 305

[ScoreTextNotesScore5]
Inherits = ScoreTextNotesScore4
X = 520

[ScoreTextLineBonus5]
Inherits = ScoreTextLineBonus4
X = 305

[ScoreTextLineBonusScore5]
Inherits = ScoreTextLineBonusScore4
X = 520

[ScoreTextGoldenNotes5]
Inherits = ScoreTextGoldenNotes4
X = 305

[ScoreTextGoldenNotesScore5]
Inherits = ScoreTextGoldenNotesScore4
X = 520

[ScoreStaticBoxDark5]
Inherits = ScoreStaticBoxDark4
X = 280
Color = P2Dark

[ScoreStaticBoxLight5]
Inherits = ScoreStaticBoxLight4
X = 280
Color = P2Light

[ScoreStaticBoxLightest5]
Inherits = ScoreStaticBoxLightest4
X = 280
Color = P2Lightest

[ScoreTextTotal5]
Inherits = ScoreTextTotal4
X = 315

[ScoreTextTotalScore5]
Inherits = ScoreTextTotalScore4
X = 520

#lines
[ScorePlayer5Static1]
Inherits = ScorePlayer4Static1
X = 280

[ScorePlayer5Static2]
Inherits = ScorePlayer4Static2
X = 280

[ScorePlayer5Static3]
Inherits = ScorePlayer4Static3
X = 280

[ScorePlayer5Static4]
Inherits = ScorePlayer4Static4
X = 280

#ScoreBar
[ScoreStaticBackLevel5]
Inherits = ScoreStaticBackLevel4
X = 284
Color = P5Lightest
 
[ScoreStaticBackLevelRound5]
Inherits = ScoreStaticBackLevelRound4
X = 284
Color = P5Lightest

[ScoreStaticLevel5]
Inherits = ScoreStaticLevel4
X = 284
Color = P5Dark

[ScoreStaticLevelRound5]
Inherits = ScoreStaticLevelRound4
X = 284
Color = P5Dark

[ScorePlayer5Static5]
Inherits = ScorePlayer4Static5
X = 280
Color = P2Dark

[ScorePlayer5Static6]
Inherits = ScorePlayer4Static6
X = 280

[ScorePlayer5Static7]
Inherits = ScorePlayer4Static7
X = 280
Color = P2Dark

[ScorePlayer5Text1]
Inherits = ScorePlayer4Text1
Text = P2
X = 284

[ScorePlayer5Avatar]
Inherits = ScorePlayer4Avatar
X = 417

[ScorePlayer5Static8]
Inherits = ScorePlayer4Static8
X = 409
Color = P2Dark

# P L A Y E R  T H R E E (mirrors player 1)
[ScoreTextName6]
Inherits = ScoreTextName4
X = 540
Text = P3

# Rating
[ScoreStaticRatingPicture6]
Inherits = ScoreStaticRatingPicture4
X = 680

[ScoreTextScore6]
Inherits = ScoreTextScore4
X = 717

[ScoreTextNotes6]
Inherits = ScoreTextNotes4
X = 565

[ScoreTextNotesScore6]
Inherits = ScoreTextNotesScore4
X = 780

[ScoreTextLineBonus6]
Inherits = ScoreTextLineBonus4
X = 565

[ScoreTextLineBonusScore6]
Inherits = ScoreTextLineBonusScore4
X = 780

[ScoreTextGoldenNotes6]
Inherits = ScoreTextGoldenNotes4
X = 565

[ScoreTextGoldenNotesScore6]
Inherits = ScoreTextGoldenNotesScore4
X = 780

[ScoreStaticBoxDark6]
Inherits = ScoreStaticBoxDark4
X = 540
Color = P3Dark

[ScoreStaticBoxLight6]
Inherits = ScoreStaticBoxLight4
X = 540
Color = P3Light

[ScoreStaticBoxLightest6]
Inherits = ScoreStaticBoxLightest4
X = 540
Color = P3Lightest

[ScoreTextTotal6]
Inherits = ScoreTextTotal4
X = 575

[ScoreTextTotalScore6]
Inherits = ScoreTextTotalScore4
X = 780

#lines
[ScorePlayer6Static1]
Inherits = ScorePlayer4Static1
X = 540

[ScorePlayer6Static2]
Inherits = ScorePlayer4Static2
X = 540

[ScorePlayer6Static3]
Inherits = ScorePlayer4Static3
X = 540

[ScorePlayer6Static4]
Inherits = ScorePlayer4Static4
X = 540

#ScoreBar
[ScoreStaticBackLevel6]
Inherits = ScoreStaticBackLevel4
X = 544
Color = P6Lightest

[ScoreStaticBackLevelRound6]
Inherits = ScoreStaticBackLevelRound4
X = 544
Color = P6Lightest

[ScoreStaticLevel6]
Inherits = ScoreStaticLevel4
X = 544
Color = P6Dark

[ScoreStaticLevelRound6]
Inherits = ScoreStaticLevelRound4
X = 544
Color = P6Dark

[ScorePlayer6Static5]
Inherits = ScorePlayer4Static5
X = 540
Color = P3Dark

[ScorePlayer6Static6]
Inherits = ScorePlayer4Static6
X = 540
 
[ScorePlayer6Static7]
Inherits = ScorePlayer4Static7
X = 540
Color = P3Dark

