# OptionsSub* contains resusable theming for all sub options screens (Game, Graphics, etc.)
[OptionsSubBackground]
Tex = OptionsBG

[OptionsSubStatic1]
X = 40
Y = 22
W = 25
H = 23
Color = White
Tex = IconOption
Type = Transparent

[OptionsSubText1]
X = 70
Y = 5
Color = White
Size = 54
Text = SING_OPTIONS

[OptionsSubStatic2]
Inherits = DefaultBar1

[OptionsSubTextDescription]
X = 70
Y = 60
Color = ColorLightest
Size = 30

[OptionsSubStatic3]
Inherits = DefaultBar2

[OptionsSubTextWhereAmI]
Inherits = DefaultTextWhereAmI

[OptionsSubLegendStatic1]
Inherits = DefaultLegendStatic
Tex = ButtonNavi

[OptionsSubLegendText1]
Inherits = DefaultLegendText
Z = 0.5
Text = SING_LEGEND_NAVIGATE

[OptionsSubLegendStatic2]
Inherits = DefaultLegendStatic
X = 400
Tex = ButtonEsc

[OptionsSubLegendText2]
Inherits = DefaultLegendText
X = 440
Z = 0.5
Text = SING_LEGEND_ESC

[OptionsSubArea]
X = 49
Y = 130
W = 685
H = 315
WidgetVSpacing = 5
ButtonBackVSpacing = 15

[OptionsSubScrollBar]
HSpacing = 5
W = 8
Color = GrayLightest
HColor = White
CColor = Gray

[OptionsSubSelectSlide]
Inherits = DefaultSelectSlide
Text = SING_OPTIONS_GAME_SORTING
X = 70
W = 250
H = 35
SkipX = 10

[OptionsSubButton]
X = 70
W = 660
H = 35
Tex = MainBar
Color = ColorLight
DColor = ColorDark
Type = Transparent
Texts = 1

[OptionsSubButtonText1]
X = 330
Y = 3
Align = 1
Color = White
Size = 30
Text = 

[OptionsSubButtonExit]
X = 70
W = 250
H = 35
Tex = Button
Color = ColorLight
DColor = ColorDark
Type = Transparent
Reflection = 1
ReflectionSpacing = 2

