[EditBackground]
Tex = EditBG

# main icon
[EditStatic1]
X = 65
Y = 150
W = 25
H = 25
Color = White
Tex = IconEdit
Type = Transparent
# Type = Colorized

# main icon title
[EditText1]
X = 95
Y = 115
Color = White
Font = 0
Style = 0
Size = 54
Align = 0
Text = SING_EDIT

# main icon subtitle
[EditText2]
X = 95
Y = 170
Color = ColorLightest
Font = 0
Style = 0
Size = 30
Align = 0
Text = SING_EDIT_MENU_DESCRIPTION

[EditTextDescription]
X = 95
Y = 195
Color = White
Font = 0
Style = 0
Size = 30
Align = 0
Text = SING_EDIT_TEXTDESCRIPTION

# Navigate button text
[EditText3]
Inherits = DefaultLegendText
Text = SING_EDIT_NAVIGATE

# Select button text
[EditText4]
Inherits = DefaultLegendText
X = 440
Text = SING_EDIT_SELECT

# Esc button text
[EditText5]
Inherits = DefaultLegendText
X = 590
Text = SING_EDIT_EXIT

[EditText6]
Inherits = DefaultTextWhereAmI
Text = SING_EDIT_WHEREAMI

[EditStatic2]
Inherits = DefaultBar1
Z = 0.4

[EditStatic3]
Inherits = DefaultBar2
Z = 0.4

[EditStatic4]
Inherits = DefaultLegendStatic
Z = 0.5
Tex = ButtonNavi

[EditStatic5]
Inherits = DefaultLegendStatic
X = 400
Z = 0.5
Tex = ButtonEnter

[EditStatic6]
Inherits = DefaultLegendStatic
X = 550
Z = 0.952
Tex = ButtonEsc

[EditButtonConvert]
Inherits = DefaultFadeButton
X = 250
Y = 270

[EditButtonConvertText1]
Inherits = DefaultButtonFadeText
Text = SING_EDIT_BUTTON_CONVERT

[EditButtonExit]
Inherits = EditButtonConvert
X = 405

[EditButtonExitText1]
Inherits = DefaultButtonFadeText
Text = SING_EDIT_BUTTON_EXIT

[EditConvertBackground]
Tex = EditBG

# main icon
[EditConvertStatic1]
X = 65
Y = 22
W = 25
H = 25
Color = White
Tex = IconEdit
Type = Transparent
# Type = Colorized

# main icon title
[EditConvertText1]
X = 95
Y = 5
Color = White
Font = 0
Style = 0
Size = 54
Align = 0
Text = SING_EDIT_CONVERT

# main icon subtitle
[EditConvertText2]
X = 95
Y = 60
Color = ColorLightest
Font = 0
Style = 0
Size = 30
Align = 0
Text = SING_EDIT_CONVERT_MENU_DESCRIPTION

[EditConvertTextDescription]
X = 95
Y = 195
Color = White
Font = 0
Style = 0
Size = 30
Align = 0
Text = SING_EDIT_CONVERT_TEXTDESCRIPTION

# Navigate button text
[EditConvertText3]
Inherits = DefaultLegendText
Text = SING_EDIT_CONVERT_NAVIGATE

# Select button text
[EditConvertText4]
Inherits = DefaultLegendText
X = 440
Text = SING_EDIT_CONVERT_SELECT

# Esc button text
[EditConvertText5]
Inherits = DefaultLegendText
X = 590
Text = SING_EDIT_CONVERT_EXIT

[EditConvertText6]
Inherits = DefaultTextWhereAmI
Text = SING_EDIT_CONVERT_WHEREAMI

[EditConvertStatic2]
Inherits = DefaultBar1
Z = 0.4

[EditConvertStatic3]
Inherits = DefaultBar2
Z = 0.4

[EditConvertStatic4]
Inherits = DefaultLegendStatic
Z = 0.5
Tex = ButtonNavi

[EditConvertStatic5]
Inherits = DefaultLegendStatic
X = 400
Z = 0.5
Tex = ButtonEnter

[EditConvertStatic6]
Inherits = DefaultLegendStatic
X = 550
Z = 0.952
Tex = ButtonEsc

[EditConvertButtonOpen]
Inherits = DefaultButton
X = 90
Y = 100
Reflection = 1
ReflectionSpacing = 5

[EditConvertButtonOpenText1]
Inherits = DefaultButtonText
Text = SING_EDIT_CONVERT_BUTTON_OPEN

[EditConvertButtonPlay]
Inherits = EditConvertButtonOpen
X = 215

[EditConvertButtonPlayText1]
Inherits = DefaultButtonText
Text = SING_EDIT_CONVERT_BUTTON_PLAY

[EditConvertButtonPlaySelected]
Inherits = EditConvertButtonOpen
X = 340

[EditConvertButtonPlaySelectedText1]
Inherits = DefaultButtonText
Text = SING_EDIT_CONVERT_BUTTON_PLAYSELECTED

[EditConvertButtonStop]
Inherits = EditConvertButtonOpen
X = 465

[EditConvertButtonStopText1]
Inherits = DefaultButtonText
Text = SING_EDIT_CONVERT_BUTTON_STOP

[EditConvertButtonSave]
Inherits = EditConvertButtonOpen
X = 590

[EditConvertButtonSaveText1]
Inherits = DefaultButtonText
Text = SING_EDIT_CONVERT_BUTTON_SAVE

[EditOpenBackground]
Tex = EditBG

# main icon
[EditOpenStatic1]
X = 65
Y = 22
W = 25
H = 25
Color = White
Tex = IconEdit
Type = Transparent
# Type = Colorized

# main icon title
[EditOpenText1]
X = 95
Y = 5
Color = White
Font = 0
Style = 0
Size = 54
Align = 0
Text = SING_EDIT_OPEN

# main icon subtitle
[EditOpenText2]
X = 95
Y = 60
Color = ColorLightest
Font = 0
Style = 0
Size = 30
Align = 0
Text = SING_EDIT_OPEN_MENU_DESCRIPTION

[EditOpenText3]
X = 100
Y = 208
Color = ColorLightest
Font = 0
Style = 0
Size = 24
Align = 0
Text = SING_EDIT_OPEN_PATH

[EditOpenTextDescription]
X = 95
Y = 195
Color = White
Font = 0
Style = 0
Size = 30
Align = 0
Text = SING_EDIT_OPEN_TEXTDESCRIPTION

# Navigate button text
[EditOpenText4]
Inherits = DefaultLegendText
Text = SING_EDIT_OPEN_NAVIGATE

# Select button text
[EditOpenText5]
Inherits = DefaultLegendText
X = 440
Text = SING_EDIT_OPEN_SELECT

# Esc button text
[EditOpenText6]
Inherits = DefaultLegendText
X = 590
Text = SING_EDIT_OPEN_EXIT

[EditOpenText7]
Inherits = DefaultTextWhereAmI
Text = SING_EDIT_OPEN_WHEREAMI

[EditOpenStatic2]
Inherits = DefaultBar1

[EditOpenStatic3]
Inherits = DefaultBar2
Z = 0.4

[EditOpenStatic4]
Inherits = DefaultLegendStatic
Z = 0.5
Tex = ButtonNavi

[EditOpenStatic5]
Inherits = DefaultLegendStatic
X = 400
Z = 0.5
Tex = ButtonEnter

[EditOpenStatic6]
Inherits = DefaultLegendStatic
X = 550
Z = 0.952
Tex = ButtonEsc

[EditOpenButtonLoad]
Inherits = DefaultFadeButton
X = 250
Y = 270

[EditOpenButtonLoadText1]
Inherits = DefaultButtonFadeText
Text = SING_EDIT_OPEN_BUTTON_LOAD

[EditOpenButtonBack]
Inherits = EditOpenButtonLoad
X = 405

[EditOpenButtonBackText1]
Inherits = DefaultButtonFadeText
Text = SING_EDIT_OPEN_BUTTON_BACK

[EditOpenButtonFileName]
Inherits = DefaultButton
X = 150
Y = 200
W = 550
H = 40

[EditOpenButtonFileNameText1]
Inherits = DefaultButtonText
X = 10
Y = 8
Align = 0
Text = 

