[SongMenuBackground]
Type=Fade
ColR=0
ColG=0
ColB=0
Alpha=0.3

[SongMenuStatic1]
Tex = interface_dialog_backgroundtop
X = 500
Y = 120
W = 280
H = 200
Z = 0.96
Color = White
Type = Transparent

[SongMenuStatic2]
X = 508
Y = 135
W = 24
H = 24
Color = White
Tex = icon_song_menu
Type = Colorized
Z = 0.97

[SongMenuTextMenu]
X = 538
Y = 129
Z = 0.97
Color = ColorLight
Size = 36
Text = MENU

[SongMenuButton1]
X = 530
Y = 178
Z = 0.97
W = 220
H = 25
Tex = Rectangle
Color = ColorLight
DColor = ColorDark
Type = Colorized
Texts = 1

[SongMenuButton1Text1]
X = 6
Y = 0
Z = 0.97
Color = White
Size = 24
Text = SONG_MENU_PLAY

# shows up instead of Button 1
# in some song menus
[SongMenuSelectSlide1]
TexSBG = Rectangle
Text = 
TypeSBG = Colorized
ShowArrows = 1
OneItemOnly = 1
X = 530
Y = 178
W = 0
H = 25
Z = 0.97
SkipX = 0
SBGW = 220
TextSize = 24
Color = ColorLight
DColor = ColorDark
TColor = White
TDColor = White
SBGColor = ColorLight
SBGDColor = ColorDark
STColor = White
STDColor = White

[SongMenuButton2]
Inherits = SongMenuButton1
Y = 205

[SongMenuButton2Text1]
Inherits = SongMenuButton1Text1
Text = SONG_MENU_EDIT

# shows up instead of Button 2
# in some song menus
[SongMenuSelectSlide2]
Inherits = SongMenuSelectSlide1
Y = 205

[SongMenuButton3]
Inherits = SongMenuButton1
Y = 232

[SongMenuButton3Text1]
Inherits = SongMenuButton1Text1
Text = SONG_MENU_MODI

# shows up instead of BUtton 3
# in some song menus
[SongMenuSelectSlide3]
Inherits = SongMenuSelectSlide1
Y = 232

[SongMenuButton4]
Inherits = SongMenuButton1
Y = 259

[SongMenuButton4Text1]
Inherits = SongMenuButton1Text1
Text = SONG_MENU_CANCEL

[SongMenuButton5]
Inherits = SongMenuButton1
Y = 286

[SongMenuButton5Text1]
Inherits = SongMenuButton1Text1
Text = SONG_MENU_CANCEL

[SongJumptoBackground]
Type=Fade
ColR=0
ColG=0
ColB=0
Alpha=0.3

[SongJumptoStatic1]
Tex = interface_dialog_backgroundtop2
X = 250
Y = 0
W = 300
H = 160
Z = 0.965
Color = White
Type = Transparent

[SongJumptoStatic2]
X = 258
Y = 15
W = 24
H = 24
Color = White
Tex = icon_song_search
Type = Colorized
Z = 0.97

[SongJumptoText1]
X = 288
Y = 9
Z = 0.97
Color = ColorLight
Size = 36
Text = SONG_JUMPTO_TYPE_DESC

[SongJumptoSelectSlideType]
X = 255
Y = 58
Z = 0.97
H = 30
SBGW = 290
SkipX = 0
Size = 24
oneItemOnly = 1
showArrows = 1

#text
TColor = White
TDColor = White
#Select0r.Text.Color
STColor = White
STDColor = White

[SongJumptoButtonSearchText]
X = 255
Y = 70
Z = 0.97
W = 290
H = 50
Size = 36
Font = 0
Style = 1
Align = 0
Color = ColorLight

[SongJumptoTextFound]
X = 270
Y = 125
Color = White
Font = 0
Style = 0
Size = 20
Text = SONG_JUMPTO_HELP
Align = 0
Z = 0.97

