##############################
##          NEW'S           ##
##############################

[InsertUserPopupBackground]
Type=Fade
ColR=0
ColG=0
ColB=0
Alpha=0.4

[InsertUserPopupStatic1]
Inherits = CheckPopupStatic1
H = 220

[InsertUserPopupText1]
Inherits = CheckPopupText1
Y = 165

[InsertUserPopupText]
Inherits = CheckPopupText
Y = 215
W = 380
Size = 24

[InsertUserPopupButtonUsername]
X = 380
Y = 250
W = 160
H = 25
Tex = Button
Color = GrayLight
DColor = GrayDark
Type = Transparent
Texts = 2
Z = 1

[InsertUserPopupButtonUsernameText1]
X = 5
Y = 0
Color = Black
Font = 0
Style = 0
Size = 24
Align = 0
Z = 1

[InsertUserPopupButtonUsernameText2]
X = -120
Y = 0
Text = SING_OPTIONS_NETWORK_USERNAME
Color = White
Font = 0
Style = 0
Size = 24
Align = 0
Z = 1

[InsertUserPopupButtonPassword]
Inherits = InsertUserPopupButtonUsername
Y = 280

[InsertUserPopupButtonPasswordText1]
Inherits = InsertUserPopupButtonUsernameText1

[InsertUserPopupButtonPasswordText2]
Inherits = InsertUserPopupButtonUsernameText2
Text=SING_OPTIONS_NETWORK_PASSWORD

[InsertUserPopupButton1]
X = 285
Y = 330
W = 100
H = 25
Tex = Button
Color = ColorLight
DColor = ColorDark
Type = Transparent
Texts = 1
Z = 1

[InsertUserPopupButton1Text1]
X = 50
Y = 0
Color = White
Font = 0
Style = 0
Size = 24
Align = 1
Z = 1

[InsertUserPopupButton2]
Inherits = InsertUserPopupButton1
X = 415

[InsertUserPopupButton2Text1]
Inherits = InsertUserPopupButton1Text1

