############################
#    Send Score 1 Player   #
############################

[ScoreButtonSend1]
X = 200
Y = 505
W = 180
H = 30
Tex = ButtonSendScore
DColor = ColorLight
Color = ColorDark
Type = Transparent
Texts = 1

[ScoreButtonSend1Text1]
X = 90
Y = 4
Font = 0
Style = 0
Size = 24
Align = 1
Color = White
Text = SCORE_SEND_DESC

############################
#  Send Score 2/4 Players  #
############################

[ScoreButtonSend2]
Inherits = ScoreButtonSend1
X = 310
Y = 100

[ScoreButtonSend2Text1]
Inherits = ScoreButtonSend1Text1

############################
#  Send Score 3/6 Players  #
############################

[ScoreButtonSend3]
Inherits = ScoreButtonSend2

[ScoreButtonSend3Text1]
Inherits = ScoreButtonSend1Text1

################################
##      Send Score PopUp      ##
################################

[SendScorePopup]

[SendScorePopupBackground]
Type=Fade
ColR=0
ColG=0
ColB=0
Alpha=0.4

[SendScorePopupStatic1]
Tex = interface_dialog_background2
X = 200
Y = 150
W = 400
H = 280
Z = 1
Color = White
Type = Transparent
Reflection = 1
ReflectionSpacing = 15

[SendScorePopupText1]
X = 400
Y = 157
W = 400
Color = ColorLight
Font = 0
Style = 0
Size = 30
Align = 1
Z = 1

[SendScorePopupSelectSlide1]
Text = SCORE_SEND_PLAYER
TexSBG = Rectangle
TypeSBG = Colorized
ShowArrows = 1
OneItemOnly = 1
X = 220
Y = 220
W = 120
H = 25
Z = 1
SkipX = 10
SBGW = 220
TextSize = 24
Color = ColorLight
DColor = ColorDark
TColor = White
TDColor = White
SBGColor = ColorLight
SBGDColor = ColorDark
STColor = White
STDColor = White

[SendScorePopupSelectSlide2]
Inherits = SendScorePopupSelectSlide1
Text = SING_OPTIONS_NETWORK_WEBSITE
Y = 250

[SendScorePopupSelectSlide3]
Inherits = SendScorePopupSelectSlide1
Text = SING_OPTIONS_NETWORK_USERNAME
Y = 280

[SendScorePopupButtonUsername]
Inherits = InsertUserPopupButtonUsername
Y = 320

[SendScorePopupButtonUsernameText1]
Inherits = InsertUserPopupButtonUsernameText1

[SendScorePopupButtonUsernameText2]
Inherits = InsertUserPopupButtonUsernameText2

[SendScorePopupButtonPassword]
Inherits = SendScorePopupButtonUsername
Y = 350

[SendScorePopupButtonPasswordText1]
Inherits = InsertUserPopupButtonUsernameText1

[SendScorePopupButtonPasswordText2]
Inherits = InsertUserPopupButtonPasswordText2

[SendScorePopupButton1]
Inherits = InsertUserPopupButton1
X = 295
Y = 390

[SendScorePopupButton1Text1]
Inherits = InsertUserPopupButton1Text1

[SendScorePopupButton2]
Inherits = SendScorePopupButton1
X = 405

[SendScorePopupButton2Text1]
Inherits = InsertUserPopupButton1Text1

