##########################################
##										##
##             JUKEBOX MODE		        ##
##										##
##########################################

[JukeboxTimeBackground]
Tex = JukeboxTimeBar1
X = 325
Y = 460
W = 315
H = 25
Color = White
Type = Transparent

[JukeboxTimeProgress]
X = 339
Y = 468
W = 248
H = 8
Color = ColorDark

[JukeboxSongListBackground]
Tex = JukeboxSongListBackground
X = 150
Y = 55
W = 500
H = 440
Color = White
Type = Colorized

[JukeboxListText]
X = 160
Y = 65
W = 500
Color = White
Font = 0
Style = 1
Size = 24
Align = 0
Z = 1
Text=JUKEBOX_SONGLIST

[JukeboxCountText]
X = 636
Y = 74
W = 100
Color = White
Font = 0
Style = 1
Size = 18
Align = 2
Z = 1

[JukeboxSongDescription]
X = 160
Y = 110
W = 480
H = 25
Tex = JukeboxSongListBackground
Color = ColorDark
DColor = White
Type = Colorized
Texts=2

[JukeboxSongDescriptionText1]
X = 10
Y = 3
W = 100
Color = White
Font = 0
Style = 0
Size = 20
Align = 0
Z = 1

[JukeboxSongDescriptionText2]
Inherits = JukeboxSongDescriptionText1
X = 470
Color = WhiteGray
Align = 2

[JukeboxFind]
X = 360
Y = 385
W = 280
H = 25
Tex = JukeboxSongListBackground
Color = ColorDark
DColor = White
Type = Colorized
Texts=2

[JukeboxFindText1]
X = 10
Y = 3
W = 220
Color = White
Font = 0
Style = 1
Size = 19
Align = 0
Z = 1

[JukeboxFindText2]
X = -80
Y = 4
W = 220
Color = White
Font = 0
Style = 1
Size = 18
Align = 0
Z = 1
Text = JUKEBOX_FIND

[JukeboxSort]
Inherits = JukeboxFind
Y = 423
W = 108

[JukeboxSortText1]
X = 54
Y = 4
W = 100
Color = White
Font = 0
Style = 1
Size = 18
Align = 1
Z = 1
Text = OPTION_VALUE_ARTIST

[JukeboxSortText2]
Inherits = JukeboxFindText2
Text = JUKEBOX_SORT

[JukeboxRandom]
Inherits = JukeboxSort
X = 471
W = 40
Tex = JukeboxRandom
Texts = 0

[JukeboxRepeat]
Inherits = JukeboxRandom
X = 514
Tex = JukeboxRepeat

[JukeboxLyric]
Inherits = JukeboxRandom
X = 557
Tex = JukeboxLyric

[JukeboxOptions]
Inherits = JukeboxRandom
X = 600
Tex = JukeboxOptions

[JukeboxSongListClose]
X = 600
Y = 55
W = 40
H = 15
Tex = JukeboxClose
Color = ColorDark
DColor = White
Type = Colorized

[JukeboxSongListFixPin]
Inherits = JukeboxSongListClose
X = 570
W = 25
Tex = JukeboxFix

[JukeboxSongCover]
X = 160
Y = 385
W = 110
H = 100

[JukeboxStaticActualSong1]
X = 20
Y = 20
W = 104
H = 94
Tex = JukeboxCurrentSongBackground
Color = ColorDark
Type = Transparent

[JukeboxStaticActualSongCover]
X = 22
Y = 22
W = 100
H = 90

[JukeboxTextActualSongArtist]
X = 140
Y = 38
Color = White
Font = 0
Style = 2
Size = 26
Align = 0
Z = 1

[JukeboxTextActualSongTitle]
Inherits = JukeboxTextActualSongArtist
Y = 65
Color = ColorDark
Size = 36

[JukeboxSongListUp]
X = 160
Y = 95
W = 480
H = 15
Tex = JukeboxSongListUp
Color = ColorDark
DColor = White
Type = Colorized

[JukeboxSongListDown]
Inherits = JukeboxSongListUp
Y = 360
Tex = JukeboxSongListDown

[JukeboxPlayPause]
X = 280
Y = 460
W = 40
H = 25
Tex = JukeboxSongMenuPlayPause
Color = ColorDark
DColor = White
Type = Colorized

[JukeboxSongMenuBackground]
Tex = JukeboxSongListBackground
X = 150
Y = 0
W = 500
H = 35
Color = White
Type = Colorized

[JukeboxSongMenuTimeBackground]
Tex = JukeboxSongMenuTimeBar
X = 210
Y = 5
W = 250
H = 25
Color = White
Type = Transparent

[JukeboxSongMenuTimeProgress]
X = 217
Y = 14
W = 182
H = 9
Color = ColorDark

[JukeboxSongMenuTextTime]
X = 450
Y = 11
W = 35
Font = 0
Style = 1
Size = 15
Color = White
Align = 2

[JukeboxSongMenuPlayPause]
X = 160
Y = 5
W = 40
H = 25
Tex = JukeboxSongMenuPlayPause
Color = ColorDark
DColor = White
Type = Colorized

[JukeboxSongMenuPrevious]
Inherits = JukeboxSongMenuPlayPause
X = 464
Tex = JukeboxSongMenuPrevious

[JukeboxSongMenuNext]
Inherits = JukeboxSongMenuPlayPause
X = 507
Tex = JukeboxSongMenuNext

[JukeboxSongMenuOptions]
Inherits = JukeboxSongMenuPlayPause
X = 557
Tex = JukeboxOptions

[JukeboxSongMenuPlaylist]
Inherits = JukeboxSongMenuPlayPause
X = 600
Tex = JukeboxSongMenuPlaylist

[JukeboxSongOptionsBackground]
Inherits = JukeboxSongListBackground
Tex = JukeboxSongOptionsBackground

[JukeboxSongOptionsClose]
Inherits = JukeboxSongListClose

[JukeboxSongOptionsDefault]
X = 160
Y = 455
W = 120
H = 25
Tex = JukeboxSongListBackground
Color = ColorDark
DColor = White
Type = Colorized
Texts = 1

[JukeboxSongOptionsDefaultText1]
X = 60
Y = 4
W = 120
Font = 0
Style = 1
Size = 18
Color = White
Align = 1
Text = JUKEBOX_SONGOPTIONS_DEFAULT

[JukeboxSongOptionsSave]
Inherits = JukeboxSongOptionsDefault
X = 515

[JukeboxSongOptionsSaveText1]
Inherits = JukeboxSongOptionsDefaultText1
Text = JUKEBOX_SONGOPTIONS_SAVE

[JukeboxSongOptionsTextSaved]
X = 500
Y = 459
W = 120
Font = 0
Style = 1
Size = 18
Color = White
Align = 2
Text = JUKEBOX_SONGOPTIONS_OPTIONSSAVED

[JukeboxSongOptionsVideoText]
X = 160
Y = 65
W = 500
Color = White
Font = 0
Style = 1
Size = 20
Align = 0
Z = 1
Text=JUKEBOX_SONGOPTIONS_VIDEO

[JukeboxSongOptionsLyricText]
Inherits = JukeboxSongOptionsVideoText
Y = 198
Text=JUKEBOX_SONGOPTIONS_LYRIC

[JukeboxSongOptionsVideoAspectSlide]
TexSBG=JukeboxSongListBackground
Text=JUKEBOX_SONGOPTIONS_VIDEO_ASPECT
TypeSBG=Colorized
ShowArrows=1
OneItemOnly=1
X=180
Y=100
W=200
H=20
Z=0.97
SkipX=0
SBGW=220
TextSize=18

Color=ColorLight
DColor=ColorDark
TColor=White
TDColor=White

SBGColor=ColorDark
SBGDColor=Black
STColor=White
STDColor=White

[JukeboxSongOptionsVideoWidthSlide]
Inherits = JukeboxSongOptionsVideoAspectSlide
Text=JUKEBOX_SONGOPTIONS_VIDEO_WIDTH
Y=130

[JukeboxSongOptionsVideoHeightSlide]
Inherits = JukeboxSongOptionsVideoAspectSlide
Text=JUKEBOX_SONGOPTIONS_VIDEO_HEIGHT
Y=160

[JukeboxSongOptionsLyricPositionSlide]
Inherits = JukeboxSongOptionsVideoAspectSlide
Text=JUKEBOX_SONGOPTIONS_LYRIC_POSITION
Y=233

[JukeboxSongOptionsLyricAlphaSlide]
Inherits = JukeboxSongOptionsVideoAspectSlide
Text=JUKEBOX_SONGOPTIONS_LYRIC_ALPHA
Y=263

[JukeboxSongOptionsLyricLineSlide]
Inherits = JukeboxSongOptionsVideoAspectSlide
Text=JUKEBOX_SONGOPTIONS_LYRIC_LINE
Y=293

[JukeboxSongOptionsLyricPropertySlide]
Inherits = JukeboxSongOptionsVideoAspectSlide
Text=JUKEBOX_SONGOPTIONS_LYRIC_PROPERTY
Y=323

[JukeboxSongOptionsLyricColorSlide]
Inherits = JukeboxSongOptionsVideoAspectSlide
Text=JUKEBOX_SONGOPTIONS_LYRIC_COLOR
Y=353

[JukeboxSongOptionsLyricSelectR]
Inherits = JukeboxSongOptionsVideoAspectSlide
Tex= JukeboxSongListBackground
Type = Colorized
Text = JUKEBOX_SONGOPTIONS_LYRIC_RGB_RED
X = 270
Y = 380
W = 100
H = 15
SkipX = 10
TextSize = 14

Color=ColorDark
DColor=White

SBGColor=White
SBGDColor=White

[JukeboxSongOptionsLyricRed]
X = 380
Y = 380
W = 220
H = 15
Z = 1
Alpha = 0.5
Tex = Picker
Type = Transparent

[JukeboxSongOptionsLyricPointerR]
X = 380
Y = 378
W = 1
H = 18
Z = 1
Tex = Picker
Color = Black 
Type = Transparent

[JukeboxSongOptionsLyricSelectG]
Inherits = JukeboxSongOptionsLyricSelectR
Text = JUKEBOX_SONGOPTIONS_LYRIC_RGB_GREEN
Y = 400

[JukeboxSongOptionsLyricGreen]
Inherits = JukeboxSongOptionsLyricRed
Y = 400

[JukeboxSongOptionsLyricPointerG]
Inherits = JukeboxSongOptionsLyricPointerR
Y = 398

[JukeboxSongOptionsLyricSelectB]
Inherits = JukeboxSongOptionsLyricSelectR
Text = JUKEBOX_SONGOPTIONS_LYRIC_RGB_BLUE
Y = 420

[JukeboxSongOptionsLyricBlue]
Inherits = JukeboxSongOptionsLyricRed
Y = 420

[JukeboxSongOptionsLyricPointerB]
Inherits = JukeboxSongOptionsLyricPointerR
Y = 418

