#############################
#							#
#   		 Edit			#
#							#
#############################

[EditSub]
[EditSubBackground]
Tex = EditSubBG

# main icon
[EditSubStatic1]
X = 30
Y = 15
W = 25
H = 25
Color = White
Tex = IconEdit
Type = Transparent
# Type = Colorized

# main icon title
[EditSubText1]
X = 60
Y = 5
Color = White
Font = 0
Style = 0
Size = 44
Align = 0
Text = SING_EDIT

[EditSubStatic2]
Inherits = DefaultBar1
Z = 0.4

[EditSubStatic3]
Inherits = DefaultBar2
Z = 0.4

# info text
[EditSubTextInfo]
X = 265
Y = 551
Color = Black
Font = 0
Style = 0
Size = 18
Align = 0
Text =

# current tone text
[EditSubTextCurrentTone]
X = 480
Y = 295
Color = Yellow
Font = 0
Style = 0
Size = 16
Align = 0
Text =

# header background
[EditSubHeaderBackground]
X = 20
Y = 56
W = 760
H = 226
Color = GrayLightest
Alpha = 0.5

# current note info background
[EditSubCurrentNoteInfoBackground]
Inherits = EditSubHeaderBackground
Y = 290
H = 26

# volume slider background
[EditSubVolumeSliderBackground]
X = 600
Y = 3
W = 180
H = 48
Color = GrayLightest
Alpha = 0.5

# notes background
[EditSubNotesBackground]
Inherits = EditSubHeaderBackground
Y = 324
H = 135

# sentence background
[EditSubSentenceBackground]
Inherits = EditSubHeaderBackground
Y = 467
H = 38

# lyrics sentence
[EditSubTextSentence]
X = 400
Y = 467
Color = Red
DColor = Black
Font = 0
Style = 0
Size = 40
Align = 1
Text =

# P1 info bar
[EditSubP1InfoBarBackground]
Inherits = EditSubHeaderBackground
Y = 513
H = 10

# P2 info bar
[EditSubP2InfoBarBackground]
Inherits = EditSubHeaderBackground
Y = 530
H = 10

[EditSubTitle]
X = 30
Y = 60
W = 78
H = 18
SkipX = 2
TextSize = 16
Text = EDIT_TITLE
Type = Transparent
TexSBG = MainBar
TypeSBG = Transparent
ShowArrows = 0
SBGW = 392
Align = 0

DColor = ColorDark
Color = ColorLight
TColor = Black
TDColor = GrayDark
 
SBGDColor = ColorDark
SBGColor = ColorLight
STColor = White
STDColor = GrayDark

[EditSubArtist]
Inherits = EditSubTitle
Y = 80
Text = EDIT_ARTIST

[EditSubLanguage]
Inherits = EditSubTitle
Y = 100
Text = EDIT_LANGUAGE
SBGW = 156

[EditSubEdition]
Inherits = EditSubLanguage
X = 268
W = 76
Text = EDIT_EDITION

[EditSubGenre]
Inherits = EditSubTitle
Y = 120
Text = EDIT_GENRE
SBGW = 76

[EditSubYear]
Inherits = EditSubGenre
X = 188
Text = EDIT_YEAR

[EditSubCreator]
Inherits = EditSubGenre
X = 346
Text = EDIT_CREATOR

[EditSubMP3]
Inherits = EditSubTitle
Y = 140
Text = EDIT_MP3
ArrowW = 16
ArrowH = 32
ShowArrows = 1
OneItemOnly = 1

[EditSubSlideCover]
Inherits = EditSubMP3
Y = 160
Text = EDIT_COVER
TexSBG = SelectBG

[EditSubSlideBackground]
Inherits = EditSubSlideCover
Y = 180
Text = EDIT_BACKGROUND

[EditSubSlideVideo]
Inherits = EditSubSlideCover
Y = 200
Text = EDIT_VIDEO

[EditSubVideoGap]
Inherits = EditSubTitle
Y = 220
Text = EDIT_VIDEOGAP
SBGW = 76

[EditSubBPM]
Inherits = EditSubVideoGap
Y = 240
Text = EDIT_BPM

[EditSubGAP]
Inherits = EditSubVideoGap
Y = 260
Text = EDIT_GAP

[EditSubStartTag]
Inherits = EditSubVideoGap
X = 188
Text = EDIT_STARTTAG
SBGDColor = GrayLight
SBGColor = GrayLight

[EditSubPreviewStart]
Inherits = EditSubBPM
X = 188
Text = EDIT_PREVIEWSTART

[EditSubMedleyStart]
Inherits = EditSubGAP
X = 188
Text = EDIT_MEDLEYSTART

[EditSubEndTag]
Inherits = EditSubStartTag
X = 346
Text = EDIT_ENDTAG

[EditSubRelative]
Inherits = EditSubPreviewStart
X = 346
Text = EDIT_RELATIVE

[EditSubMedleyEnd]
Inherits = EditSubMedleyStart
X = 346
Text = EDIT_MEDLEYEND

[EditSubStart]
Inherits = EditSubGAP
Y = 294
Text = EDIT_START
DColor = DarkRed
Color = LightRed
SBGDColor = Red
SBGColor = Red

[EditSubDuration]
Inherits = EditSubStart
X = 188
Text = EDIT_DURATION

[EditSubTone]
Inherits = EditSubStart
X = 346
Text = EDIT_TONE

[EditSubLyric]
Inherits = EditSubStart
X = 506
Text = EDIT_LYRIC
SBGW = 184

[EditSubSelectVolAudio]
TexSBG = SelectBG
Text = EDIT_VOLUME_AUDIO
Type = Transparent
TypeSBG = Transparent
X = 590
Y = 5
Z = 1
W = 0
H = 14
TextSize = 14
SkipX = 100
ShowArrows = 0
OneItemOnly = 1
SBGW = 80

DColor = ColorDark
Color = ColorLight
TColor = Black
TDColor = GrayDark
 
SBGDColor = ColorDark
SBGColor = ColorLight
STColor = White
STDColor = GrayDark

[EditSubSelectVolMidi]
Inherits = EditSubSelectVolAudio
Text = EDIT_VOLUME_MIDI
Y = 20

[EditSubSelectVolClick]
Inherits = EditSubSelectVolAudio
Text = EDIT_VOLUME_CLICK
Y = 35

[EditSubBackgroundImage]
X = 506
Y = 60
W = 264
H = 198
Z = 0.95
Color = Red
Tex = prevbackground
Type = Transparent

[EditSubButtonCurrentLine]
X = 20
Y = 550
Z = 1
W = 110
H = 20
Size = 20
Font = 0
Style = 1
Align = 0
Color = ColorLight
DColor = ColorLight
Tex = Leiste1
Type = Colorized
Texts = 1

[EditSubButtonCurrentLineText1]
X = 10
Y = 2
Color = White
Font = 0
Style = 1
Size = 18
Align = 0

[EditSubButtonCurrentNote]
Inherits = EditSubButtonCurrentLine
X = 130

[EditSubButtonCurrentNoteText1]
Inherits = EditSubButtonCurrentLineText1

[EditSubBarStatic1]
Tex = undo
X = 518
Y = 260
W = 18
H = 18
Type = Transparent
Color = ColorLight

[EditSubBarStatic2]
Inherits = EditSubBarStatic1
Tex = previousseq
X = 558

[EditSubBarStatic3]
Inherits = EditSubBarStatic1
Tex = nextseq
X = 584

[EditSubBarStatic4]
Inherits = EditSubBarStatic1
Tex = freestyle
X = 624

[EditSubBarStatic5]
Inherits = EditSubBarStatic1
Tex = gold
X = 650

[EditSubBarStatic6]
Inherits = EditSubBarStatic1
Tex = PlayOnly
X = 690

[EditSubBarStatic7]
Inherits = EditSubBarStatic1
Tex = playwithnote
X = 716

[EditSubBarStatic8]
Inherits = EditSubBarStatic1
Tex = playnote
X = 742

