##################################
##########     Duet     ##########
##################################

[SingLyricsDuetP2UpperBar]
X = 80
W = 640
Y = 493
H = 41
;YOffSet (+/-) for the Sing-Indicator
IndicatorYOffset = 3

[SingLyricsDuetP2LowerBar]
Inherits = SingLyricsDuetP2UpperBar
Y = 535

[SingLyricsDuetP1UpperBar]
X = 80
W = 640
Y = 7
H = 41
;YOffSet (+/-) for the Sing-Indicator
IndicatorYOffset = 3

[SingLyricsDuetP1LowerBar]
Inherits = SingLyricsDuetP1UpperBar
Y = 49

[SingLyricsBarDuet]
Inherits = SingLyricsBar
Tex = LyricBarDuet
X = 10
Y = 5

