# T H R E E  P L A Y E R  D U E T  M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingDuetP1ThreePStatic]
X = 12
Y = 99
W = 37
H = 37
Tex = AvatarFrame2
Color = P1Dark
Type = Transparent
Alpha = 1

[SingDuetP1ThreePText]
Text = PLAYERNAME
X = 58
Y = 118
Font = 0
Style = 1
Size = 18
Color = White
Align = 0

[SingDuetP1ThreePStatic2]
X = 710
Y = 100
W = 80
H = 25

[SingDuetP1ThreePTextScore]
X = 725
Y = 102
Font = 0
Style = 0
Size = 24

[SingDuetP1ThreePSingBar]
X = 710
Y = 125
W = 80
H = 6

[SingDuetP1ThreePAvatar]
X = 15
Y = 102
W = 31
H = 31
Z = 1
Alpha = 1

#Player Two
[SingDuetP2MStatic]
Inherits = SingDuetP1ThreePStatic
Y = 224
Color = P2Dark

[SingDuetP2MText]
Inherits = SingDuetP1ThreePText
Y = 243

[SingDuetP2MStatic2]
Inherits = SingDuetP1ThreePStatic2
Y = 225

[SingDuetP2MTextScore]
Inherits = SingDuetP1ThreePTextScore
Y = 227

[SingDuetP2MSingBar]
Inherits = SingDuetP1ThreePSingBar
Y = 250

[SingDuetP2MAvatar]
Inherits = SingDuetP1ThreePAvatar
Y = 227

#Player Three
[SingDuetP3RStatic]
Inherits = SingDuetP1ThreePStatic
Y = 349
Color = P3Dark

[SingDuetP3RText]
Inherits = SingDuetP1ThreePText
Y = 368

[SingDuetP3RStatic2]
Inherits = SingDuetP1ThreePStatic2
Y = 350

[SingDuetP3RTextScore]
Inherits = SingDuetP1ThreePTextScore
Y = 352

[SingDuetP3RSingBar]
Inherits = SingDuetP1ThreePSingBar
Y = 375

[SingDuetP3RAvatar]
Inherits = SingDuetP1ThreePAvatar
Y = 352

