#####################
###  screen song  ###
#####################

[SongRouletteStatic2PlayersDuetSingerP1]
X = 535
Y = 415
W = 154
H = 30
Z = 0.95
Type = Transparent
Color = P1Dark
Tex = SongDuetSinger

[SongRouletteText2PlayersDuetSingerP1]
X = 612
Y = 420
Font = 0
Style = 0
Size = 20
Align = 1
Color = White

[SongRouletteStatic2PlayersDuetSingerP2]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
Y = 445
Color = P2Dark
Tex = SongDuetSinger2
Reflection = 1
ReflectionSpacing = 1

[SongRouletteText2PlayersDuetSingerP2]
Inherits = SongRouletteText2PlayersDuetSingerP1
Y = 450

[SongRouletteStatic3PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
Y = 385

[SongRouletteText3PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1
Y = 390

[SongRouletteStatic3PlayersDuetSingerP2]
Inherits = SongRouletteStatic2PlayersDuetSingerP2
Y = 415
Tex = SongDuetSinger3

[SongRouletteText3PlayersDuetSingerP2]
Inherits = SongRouletteText2PlayersDuetSingerP1
Y = 420

[SongRouletteStatic3PlayersDuetSingerP3]
Inherits = SongRouletteStatic2PlayersDuetSingerP2
Y = 445
Color = P3Dark

[SongRouletteText3PlayersDuetSingerP3]
Inherits = SongRouletteText2PlayersDuetSingerP1
Y = 450

[SongRouletteStatic4PlayersDuetSingerP3]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
X = 545
Color = P3Dark

[SongRouletteStatic4PlayersDuetSingerP4]
Inherits = SongRouletteStatic2PlayersDuetSingerP2
X = 545
Color = P4Dark

[SongRouletteStatic6PlayersDuetSingerP4]
Inherits = SongRouletteStatic3PlayersDuetSingerP1
X = 545
Color = P4Dark

[SongRouletteStatic6PlayersDuetSingerP5]
Inherits = SongRouletteStatic3PlayersDuetSingerP2
X = 545
Color = P5Dark

[SongRouletteStatic6PlayersDuetSingerP6]
Inherits = SongRouletteStatic3PlayersDuetSingerP3
X = 545
Color = P6Dark

#############################

[SongListStatic2PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
X = 553
Y = 240

[SongListText2PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1
X = 630
Y = 245

[SongListStatic2PlayersDuetSingerP2]
Inherits = SongListStatic2PlayersDuetSingerP1
Y = 270
Color = P2Dark
Tex = SongDuetSinger2
Reflection = 1
ReflectionSpacing = 1

[SongListText2PlayersDuetSingerP2]
Inherits = SongListText2PlayersDuetSingerP1
Y = 275

[SongListStatic3PlayersDuetSingerP1]
Inherits = SongListStatic2PlayersDuetSingerP1
Y = 235

[SongListText3PlayersDuetSingerP1]
Inherits = SongListText2PlayersDuetSingerP1
Y = 240

[SongListStatic3PlayersDuetSingerP2]
Inherits = SongListStatic2PlayersDuetSingerP2
Y = 265
Color = P2Dark
Tex = SongDuetSinger3

[SongListText3PlayersDuetSingerP2]
Inherits = SongListText2PlayersDuetSingerP1
Y = 270

[SongListStatic3PlayersDuetSingerP3]
Inherits = SongListStatic2PlayersDuetSingerP2
Y = 295
Color = P3Dark

[SongListText3PlayersDuetSingerP3]
Inherits = SongListText2PlayersDuetSingerP1
Y = 300

[SongListStatic4PlayersDuetSingerP3]
Inherits = SongListStatic2PlayersDuetSingerP1
X = 565
Color = P3Dark

[SongListStatic4PlayersDuetSingerP4]
Inherits = SongListStatic2PlayersDuetSingerP2
X = 565
Color = P4Dark

[SongListStatic6PlayersDuetSingerP4]
Inherits = SongListStatic3PlayersDuetSingerP1
X = 565
Color = P4Dark

[SongListStatic6PlayersDuetSingerP5]
Inherits = SongListStatic3PlayersDuetSingerP2
X = 565
Color = P5Dark

[SongListStatic6PlayersDuetSingerP6]
Inherits = SongListStatic3PlayersDuetSingerP3
X = 565
Color = P6Dark

#############################

[SongChessboardStatic2PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
X = 310
Y = 435

[SongChessboardText2PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1
X = 387
Y = 440

[SongChessboardStatic2PlayersDuetSingerP2]
Inherits = SongChessboardStatic2PlayersDuetSingerP1
Y = 465
Color = P2Dark
Tex = SongDuetSinger2
Reflection = 1
ReflectionSpacing = 1

[SongChessboardText2PlayersDuetSingerP2]
Inherits = SongChessboardText2PlayersDuetSingerP1
Y = 470

[SongChessboardStatic3PlayersDuetSingerP1]
Inherits = SongChessboardStatic2PlayersDuetSingerP1

[SongChessboardText3PlayersDuetSingerP1]
Inherits = SongChessboardText2PlayersDuetSingerP1

[SongChessboardStatic3PlayersDuetSingerP2]
Inherits = SongChessboardStatic2PlayersDuetSingerP2
Tex = SongDuetSinger3

[SongChessboardText3PlayersDuetSingerP2]
Inherits = SongChessboardText2PlayersDuetSingerP2

[SongChessboardStatic3PlayersDuetSingerP3]
Inherits = SongChessboardStatic2PlayersDuetSingerP2
Y = 495
Color = P3Dark

[SongChessboardText3PlayersDuetSingerP3]
Inherits = SongChessboardText2PlayersDuetSingerP1
Y = 500

[SongChessboardStatic4PlayersDuetSingerP3]
Inherits = SongChessboardStatic2PlayersDuetSingerP1
X = 320
Color = P3Dark

[SongChessboardStatic4PlayersDuetSingerP4]
Inherits = SongChessboardStatic2PlayersDuetSingerP2
X = 320
Color = P4Dark

[SongChessboardStatic6PlayersDuetSingerP4]
Inherits = SongChessboardStatic3PlayersDuetSingerP1
X = 320
Color = P4Dark

[SongChessboardStatic6PlayersDuetSingerP5]
Inherits = SongChessboardStatic3PlayersDuetSingerP2
X = 320
Color = P5Dark

[SongChessboardStatic6PlayersDuetSingerP6]
Inherits = SongChessboardStatic3PlayersDuetSingerP3
X = 320
Color = P6Dark

