#####################
###  screen song  ###
#####################

[SongRouletteStatic2PlayersDuetSingerP1]
X = 535
Y = 415
W = 154
H = 30
Z = 0.95
Type = Transparent
Color = P1Dark
Tex = SongDuetSinger

[SongRouletteText2PlayersDuetSingerP1]
X = 612
Y = 420
Font = 0
Style = 0
Size = 20
Align = 1
Color = White

[SongRouletteStatic2PlayersDuetSingerP2]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
Y = 445
Color = P2Dark
Tex = SongDuetSinger2
Reflection = 1
ReflectionSpacing = 1

[SongRouletteText2PlayersDuetSingerP2]
Inherits = SongRouletteText2PlayersDuetSingerP1
Y = 450

[SongRouletteStatic3PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
Y = 385

[SongRouletteText3PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1
Y = 390

[SongRouletteStatic3PlayersDuetSingerP2]
Inherits = SongRouletteStatic2PlayersDuetSingerP2
Y = 415
Tex = SongDuetSinger3

[SongRouletteText3PlayersDuetSingerP2]
Inherits = SongRouletteText2PlayersDuetSingerP1
Y = 420

[SongRouletteStatic3PlayersDuetSingerP3]
Inherits = SongRouletteStatic2PlayersDuetSingerP2
Y = 445
Color = P3Dark

[SongRouletteText3PlayersDuetSingerP3]
Inherits = SongRouletteText2PlayersDuetSingerP1
Y = 450

[SongRouletteStatic4PlayersDuetSingerP3]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
X = 545
Color = P3Dark

[SongRouletteStatic4PlayersDuetSingerP4]
Inherits = SongRouletteStatic2PlayersDuetSingerP2
X = 545
Color = P4Dark

[SongRouletteStatic6PlayersDuetSingerP4]
Inherits = SongRouletteStatic3PlayersDuetSingerP1
X = 545
Color = P4Dark

[SongRouletteStatic6PlayersDuetSingerP5]
Inherits = SongRouletteStatic3PlayersDuetSingerP2
X = 545
Color = P5Dark

[SongRouletteStatic6PlayersDuetSingerP6]
Inherits = SongRouletteStatic3PlayersDuetSingerP3
X = 545
Color = P6Dark

#####################

[SongCarouselStatic2PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1

[SongCarouselText2PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1

[SongCarouselStatic2PlayersDuetSingerP2]
Inherits = SongRouletteStatic2PlayersDuetSingerP2

[SongCarouselText2PlayersDuetSingerP2]
Inherits = SongRouletteText2PlayersDuetSingerP2

[SongCarouselStatic3PlayersDuetSingerP1]
Inherits = SongRouletteStatic3PlayersDuetSingerP1

[SongCarouselText3PlayersDuetSingerP1]
Inherits = SongRouletteText3PlayersDuetSingerP1

[SongCarouselStatic3PlayersDuetSingerP2]
Inherits = SongRouletteStatic3PlayersDuetSingerP2

[SongCarouselText3PlayersDuetSingerP2]
Inherits = SongRouletteText3PlayersDuetSingerP2

[SongCarouselStatic3PlayersDuetSingerP3]
Inherits = SongRouletteStatic3PlayersDuetSingerP3

[SongCarouselText3PlayersDuetSingerP3]
Inherits = SongRouletteText3PlayersDuetSingerP3

[SongCarouselStatic4PlayersDuetSingerP3]
Inherits = SongRouletteStatic4PlayersDuetSingerP3

[SongCarouselStatic4PlayersDuetSingerP4]
Inherits = SongRouletteStatic4PlayersDuetSingerP4

[SongCarouselStatic6PlayersDuetSingerP4]
Inherits = SongRouletteStatic6PlayersDuetSingerP4

[SongCarouselStatic6PlayersDuetSingerP5]
Inherits = SongRouletteStatic6PlayersDuetSingerP5

[SongCarouselStatic6PlayersDuetSingerP6]
Inherits = SongRouletteStatic6PlayersDuetSingerP6

##################################

[SongSlotMachineStatic2PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
X = 295
Y = 435

[SongSlotMachineText2PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1
X = 372
Y = 440

[SongSlotMachineStatic2PlayersDuetSingerP2]
Inherits = SongSlotMachineStatic2PlayersDuetSingerP1
Y = 465
Color = P2Dark
Tex = SongDuetSinger2
Reflection = 1
ReflectionSpacing = 1

[SongSlotMachineText2PlayersDuetSingerP2]
Inherits = SongSlotMachineText2PlayersDuetSingerP1
Y = 470

[SongSlotMachineStatic3PlayersDuetSingerP1]
Inherits = SongSlotMachineStatic2PlayersDuetSingerP1
Y = 425

[SongSlotMachineText3PlayersDuetSingerP1]
Inherits = SongSlotMachineText2PlayersDuetSingerP1
Y = 430

[SongSlotMachineStatic3PlayersDuetSingerP2]
Inherits = SongSlotMachineStatic2PlayersDuetSingerP2
Y = 455
Tex = SongDuetSinger3

[SongSlotMachineText3PlayersDuetSingerP2]
Inherits = SongSlotMachineText2PlayersDuetSingerP1
Y = 460

[SongSlotMachineStatic3PlayersDuetSingerP3]
Inherits = SongSlotMachineStatic2PlayersDuetSingerP2
Y = 485
Color = P3Dark

[SongSlotMachineText3PlayersDuetSingerP3]
Inherits = SongSlotMachineText2PlayersDuetSingerP1
Y = 490

[SongSlotMachineStatic4PlayersDuetSingerP3]
Inherits = SongSlotMachineStatic2PlayersDuetSingerP1
X = 305
Color = P3Dark

[SongSlotMachineStatic4PlayersDuetSingerP4]
Inherits = SongSlotMachineStatic2PlayersDuetSingerP2
X = 305
Color = P4Dark

[SongSlotMachineStatic6PlayersDuetSingerP4]
Inherits = SongSlotMachineStatic3PlayersDuetSingerP1
X = 305
Color = P4Dark

[SongSlotMachineStatic6PlayersDuetSingerP5]
Inherits = SongSlotMachineStatic3PlayersDuetSingerP2
X = 305
Color = P5Dark

[SongSlotMachineStatic6PlayersDuetSingerP6]
Inherits = SongSlotMachineStatic3PlayersDuetSingerP3
X = 305
Color = P6Dark

#############################

[SongSlideStatic2PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1

[SongSlideText2PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1

[SongSlideStatic2PlayersDuetSingerP2]
Inherits = SongRouletteStatic2PlayersDuetSingerP2

[SongSlideText2PlayersDuetSingerP2]
Inherits = SongRouletteText2PlayersDuetSingerP2

[SongSlideStatic3PlayersDuetSingerP1]
Inherits = SongRouletteStatic3PlayersDuetSingerP1

[SongSlideText3PlayersDuetSingerP1]
Inherits = SongRouletteText3PlayersDuetSingerP1

[SongSlideStatic3PlayersDuetSingerP2]
Inherits = SongRouletteStatic3PlayersDuetSingerP2

[SongSlideText3PlayersDuetSingerP2]
Inherits = SongRouletteText3PlayersDuetSingerP2

[SongSlideStatic3PlayersDuetSingerP3]
Inherits = SongRouletteStatic3PlayersDuetSingerP3

[SongSlideText3PlayersDuetSingerP3]
Inherits = SongRouletteText3PlayersDuetSingerP3

[SongSlideStatic4PlayersDuetSingerP3]
Inherits = SongRouletteStatic4PlayersDuetSingerP3

[SongSlideStatic4PlayersDuetSingerP4]
Inherits = SongRouletteStatic4PlayersDuetSingerP4

[SongSlideStatic6PlayersDuetSingerP4]
Inherits = SongRouletteStatic6PlayersDuetSingerP4

[SongSlideStatic6PlayersDuetSingerP5]
Inherits = SongRouletteStatic6PlayersDuetSingerP5

[SongSlideStatic6PlayersDuetSingerP6]
Inherits = SongRouletteStatic6PlayersDuetSingerP6

#############################

[SongListStatic2PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
X = 553
Y = 240

[SongListText2PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1
X = 630
Y = 245

[SongListStatic2PlayersDuetSingerP2]
Inherits = SongListStatic2PlayersDuetSingerP1
Y = 270
Color = P2Dark
Tex = SongDuetSinger2
Reflection = 1
ReflectionSpacing = 1

[SongListText2PlayersDuetSingerP2]
Inherits = SongListText2PlayersDuetSingerP1
Y = 275

[SongListStatic3PlayersDuetSingerP1]
Inherits = SongListStatic2PlayersDuetSingerP1
Y = 235

[SongListText3PlayersDuetSingerP1]
Inherits = SongListText2PlayersDuetSingerP1
Y = 240

[SongListStatic3PlayersDuetSingerP2]
Inherits = SongListStatic2PlayersDuetSingerP2
Y = 265
Color = P2Dark
Tex = SongDuetSinger3

[SongListText3PlayersDuetSingerP2]
Inherits = SongListText2PlayersDuetSingerP1
Y = 270

[SongListStatic3PlayersDuetSingerP3]
Inherits = SongListStatic2PlayersDuetSingerP2
Y = 295
Color = P3Dark

[SongListText3PlayersDuetSingerP3]
Inherits = SongListText2PlayersDuetSingerP1
Y = 300

[SongListStatic4PlayersDuetSingerP3]
Inherits = SongListStatic2PlayersDuetSingerP1
X = 565
Color = P3Dark

[SongListStatic4PlayersDuetSingerP4]
Inherits = SongListStatic2PlayersDuetSingerP2
X = 565
Color = P4Dark

[SongListStatic6PlayersDuetSingerP4]
Inherits = SongListStatic3PlayersDuetSingerP1
X = 565
Color = P4Dark

[SongListStatic6PlayersDuetSingerP5]
Inherits = SongListStatic3PlayersDuetSingerP2
X = 565
Color = P5Dark

[SongListStatic6PlayersDuetSingerP6]
Inherits = SongListStatic3PlayersDuetSingerP3
X = 565
Color = P6Dark

#############################

[SongChessboardStatic2PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
X = 310
Y = 435

[SongChessboardText2PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1
X = 387
Y = 440

[SongChessboardStatic2PlayersDuetSingerP2]
Inherits = SongChessboardStatic2PlayersDuetSingerP1
Y = 465
Color = P2Dark
Tex = SongDuetSinger2
Reflection = 1
ReflectionSpacing = 1

[SongChessboardText2PlayersDuetSingerP2]
Inherits = SongChessboardText2PlayersDuetSingerP1
Y = 470

[SongChessboardStatic3PlayersDuetSingerP1]
Inherits = SongChessboardStatic2PlayersDuetSingerP1

[SongChessboardText3PlayersDuetSingerP1]
Inherits = SongChessboardText2PlayersDuetSingerP1

[SongChessboardStatic3PlayersDuetSingerP2]
Inherits = SongChessboardStatic2PlayersDuetSingerP2
Tex = SongDuetSinger3

[SongChessboardText3PlayersDuetSingerP2]
Inherits = SongChessboardText2PlayersDuetSingerP2

[SongChessboardStatic3PlayersDuetSingerP3]
Inherits = SongChessboardStatic2PlayersDuetSingerP2
Y = 495
Color = P3Dark

[SongChessboardText3PlayersDuetSingerP3]
Inherits = SongChessboardText2PlayersDuetSingerP1
Y = 500

[SongChessboardStatic4PlayersDuetSingerP3]
Inherits = SongChessboardStatic2PlayersDuetSingerP1
X = 320
Color = P3Dark

[SongChessboardStatic4PlayersDuetSingerP4]
Inherits = SongChessboardStatic2PlayersDuetSingerP2
X = 320
Color = P4Dark

[SongChessboardStatic6PlayersDuetSingerP4]
Inherits = SongChessboardStatic3PlayersDuetSingerP1
X = 320
Color = P4Dark

[SongChessboardStatic6PlayersDuetSingerP5]
Inherits = SongChessboardStatic3PlayersDuetSingerP2
X = 320
Color = P5Dark

[SongChessboardStatic6PlayersDuetSingerP6]
Inherits = SongChessboardStatic3PlayersDuetSingerP3
X = 320
Color = P6Dark

#############################

[SongMosaicStatic2PlayersDuetSingerP1]
Inherits = SongRouletteStatic2PlayersDuetSingerP1
X = 565
Y = 435

[SongMosaicText2PlayersDuetSingerP1]
Inherits = SongRouletteText2PlayersDuetSingerP1
X = 642
Y = 440

[SongMosaicStatic2PlayersDuetSingerP2]
Inherits = SongMosaicStatic2PlayersDuetSingerP1
Y = 465
Color = P2Dark
Tex = SongDuetSinger2
Reflection = 1
ReflectionSpacing = 1

[SongMosaicText2PlayersDuetSingerP2]
Inherits = SongMosaicText2PlayersDuetSingerP1
Y = 470

[SongMosaicStatic3PlayersDuetSingerP1]
Inherits = SongMosaicStatic2PlayersDuetSingerP1
Y = 420

[SongMosaicText3PlayersDuetSingerP1]
Inherits = SongMosaicText2PlayersDuetSingerP1
Y = 425

[SongMosaicStatic3PlayersDuetSingerP2]
Inherits = SongMosaicStatic2PlayersDuetSingerP2
Y = 450
Tex = SongDuetSinger3

[SongMosaicText3PlayersDuetSingerP2]
Inherits = SongMosaicText2PlayersDuetSingerP1
Y = 455

[SongMosaicStatic3PlayersDuetSingerP3]
Inherits = SongMosaicStatic2PlayersDuetSingerP2
Y = 480
Color = P3Dark

[SongMosaicText3PlayersDuetSingerP3]
Inherits = SongMosaicText2PlayersDuetSingerP1
Y = 485

[SongMosaicStatic4PlayersDuetSingerP3]
Inherits = SongMosaicStatic2PlayersDuetSingerP1
X = 575
Color = P3Dark

[SongMosaicStatic4PlayersDuetSingerP4]
Inherits = SongMosaicStatic2PlayersDuetSingerP2
X = 575
Color = P4Dark

[SongMosaicStatic6PlayersDuetSingerP4]
Inherits = SongMosaicStatic3PlayersDuetSingerP1
X = 575
Color = P4Dark

[SongMosaicStatic6PlayersDuetSingerP5]
Inherits = SongMosaicStatic3PlayersDuetSingerP2
X = 575
Color = P5Dark

[SongMosaicStatic6PlayersDuetSingerP6]
Inherits = SongMosaicStatic3PlayersDuetSingerP3
X = 575
Color = P6Dark

