#############################

#############################
##                         ## 
## 4/6 Players One Screen  ##
##                         ##
#############################

# FOUR  P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1FourPStatic]
X = 20
Y = 55
W = 50
H = 50
Tex = AvatarFrame2
Color = P1Dark
Type = Transparent
Alpha = 1

[SingP1FourPStatic2]
Tex = ScoreBG
X = 80
Y = 61
W = 100
H = 36
Color = P1Dark
Type = Colorized

[SingP1FourPTextScore]
Text = 00000
X = 98
Y = 63
Font = 0
Style = 0
Size = 30
Color = White
Align = 0

[SingP1FourPSingBar]
X = 80
Y = 95
W = 100
H = 8

[SingP1FourPAvatar]
X = 24
Y = 59
W = 42
H = 42
Z = 1
Alpha = 1

#Player Two
[SingP2FourPStatic]
Inherits = SingP1FourPStatic
X = 220
Color = P2Dark

[SingP2FourPStatic2]
Inherits = SingP1FourPStatic2
X = 280
Color = P2Dark

[SingP2FourPTextScore]
Inherits = SingP1FourPTextScore
X = 298

[SingP2FourPSingBar]
Inherits = SingP1FourPSingBar
X = 280

[SingP2FourPAvatar]
Inherits = SingP1FourPAvatar
X = 224

#Player Three
[SingP3FourPStatic]
Inherits = SingP1FourPStatic
X = 420
Color = P3Dark

[SingP3FourPStatic2]
Inherits = SingP1FourPStatic2
X = 480
Color = P3Dark

[SingP3FourPTextScore]
Inherits = SingP1FourPTextScore
X = 498

[SingP3FourPSingBar]
Inherits = SingP1FourPSingBar
X = 480

[SingP3FourPAvatar]
Inherits = SingP1FourPAvatar
X = 424

#Player Four
[SingP4FourPStatic]
Inherits = SingP1FourPStatic
X = 620
Color = P4Dark

[SingP4FourPStatic2]
Inherits = SingP1FourPStatic2
X = 680
Color = P4Dark

[SingP4FourPTextScore]
Inherits = SingP1FourPTextScore
X = 698

[SingP4FourPSingBar]
Inherits = SingP1FourPSingBar
X = 680

[SingP4FourPAvatar]
Inherits = SingP1FourPAvatar
X = 624

