# SIX  P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1SixPStatic]
X = 20
Y = 100
W = 37
H = 37
Tex = AvatarFrame2
Color = P1Dark
Type = Transparent
Alpha = 1

[SingP1SixPAvatar]
X = 23
Y = 103
W = 31
H = 31
Z = 1
Alpha = 1

[SingP1SixPStatic2]
Tex = ScoreBG
X = 20
Y = 40
W = 100
H = 36
Color = P1Dark
Type = Colorized

[SingP1SixPTextScore]
Text = 00000
X = 38
Y = 42
Font = 0
Style = 0
Size = 30
Color = White
Align = 0

[SingP1SixPSingBar]
X = 20
Y = 76
W = 100
H = 8

#Player Two
[SingP2SixPStatic]
Inherits = SingP1SixPStatic
Y = 227
Color = P2Dark

[SingP2SixPAvatar]
Inherits = SingP1SixPAvatar
Y = 230

[SingP2SixPStatic2]
Inherits = SingP1SixPStatic2
X = 150
Color = P2Dark

[SingP2SixPTextScore]
Inherits = SingP1SixPTextScore
X = 168

[SingP2SixPSingBar]
Inherits = SingP1SixPSingBar
X = 150

#Player Three
[SingP3SixPStatic]
Inherits = SingP1SixPStatic
Y = 352
Color = P3Dark

[SingP3SixPAvatar]
Inherits = SingP1SixPAvatar
Y = 355

[SingP3SixPStatic2]
Inherits = SingP1SixPStatic2
X = 280
Color = P3Dark

[SingP3SixPTextScore]
Inherits = SingP1SixPTextScore
X = 298

[SingP3SixPSingBar]
Inherits = SingP1SixPSingBar
X = 280

#Player Four
[SingP4SixPStatic]
Inherits = SingP1SixPStatic
X = 390
Color = P4Dark

[SingP4SixPAvatar]
Inherits = SingP1SixPAvatar
X = 393

[SingP4SixPStatic2]
Inherits = SingP1SixPStatic2
X = 410
Color = P4Dark

[SingP4SixPTextScore]
Inherits = SingP1SixPTextScore
X = 428

[SingP4SixPSingBar]
Inherits = SingP1SixPSingBar
X = 410

#Player Five
[SingP5SixPStatic]
Inherits = SingP2SixPStatic
X = 390
Color = P5Dark

[SingP5SixPAvatar]
Inherits = SingP2SixPAvatar
X = 393

[SingP5SixPStatic2]
Inherits = SingP1SixPStatic2
X = 540
Color = P5Dark

[SingP5SixPTextScore]
Inherits = SingP1SixPTextScore
X = 558

[SingP5SixPSingBar]
Inherits = SingP1SixPSingBar
X = 540

#Player Six
[SingP6SixPStatic]
Inherits = SingP3SixPStatic
X = 390
Color = P6Dark

[SingP6SixPAvatar]
Inherits = SingP3SixPAvatar
X = 393

[SingP6SixPStatic2]
Inherits = SingP1SixPStatic2
X = 670
Color = P6Dark

[SingP6SixPTextScore]
Inherits = SingP1SixPTextScore
X = 688

[SingP6SixPSingBar]
Inherits = SingP1SixPSingBar
X = 670

