# FOUR DUET P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1DuetFourPStatic]
X = 20
Y = 114
W = 37
H = 37
Tex = AvatarFrame2
Color = P1Dark
Type = Transparent
Alpha = 1

[SingP1DuetFourPStatic2]
Tex = ScoreBG
X = 305
Y = 117
W = 80
H = 25

[SingP1DuetFourPTextScore]
Text = 00000
X = 320
Y = 119
Font = 0
Style = 0
Size = 24

[SingP1DuetFourPSingBar]
X = 305
Y = 142
W = 80
H = 6

[SingP1DuetFourPAvatar]
X = 23
Y = 117
W = 31
H = 31
Z = 1
Alpha = 1

#Player Two
[SingP2DuetFourPStatic]
Inherits = SingP1DuetFourPStatic
Y = 294
Color = P2Dark

[SingP2DuetFourPStatic2]
Inherits = SingP1DuetFourPStatic2
Y = 297

[SingP2DuetFourPTextScore]
Inherits = SingP1DuetFourPTextScore
Y = 299

[SingP2DuetFourPSingBar]
Inherits = SingP1DuetFourPSingBar
Y = 322

[SingP2DuetFourPAvatar]
Inherits = SingP1DuetFourPAvatar
Y = 297

#Player Three
[SingP3DuetFourPStatic]
Inherits = SingP1DuetFourPStatic
X = 390
Color = P3Dark

[SingP3DuetFourPStatic2]
Inherits = SingP1DuetFourPStatic2
X = 700

[SingP3DuetFourPTextScore]
Inherits = SingP1DuetFourPTextScore
X = 715

[SingP3DuetFourPSingBar]
Inherits = SingP1DuetFourPSingBar
X = 700

[SingP3DuetFourPAvatar]
Inherits = SingP1DuetFourPAvatar
X = 393

#Player Four
[SingP4DuetFourPStatic]
Inherits = SingP2DuetFourPStatic
X = 390
Color = P4Dark

[SingP4DuetFourPStatic2]
Inherits = SingP2DuetFourPStatic2
X = 700

[SingP4DuetFourPTextScore]
Inherits = SingP2DuetFourPTextScore
X = 715

[SingP4DuetFourPSingBar]
Inherits = SingP2DuetFourPSingBar
X = 700

[SingP4DuetFourPAvatar]
Inherits = SingP2DuetFourPAvatar
X = 393

