# SIX  DUET P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1DuetSixPStatic]
X = 20
Y = 100
W = 37
H = 37
Tex = AvatarFrame2
Color = P1Dark
Type = Transparent
Alpha = 1

[SingP1DuetSixPAvatar]
X = 23
Y = 103
W = 31
H = 31
Z = 1
Alpha = 1

[SingP1DuetSixPStatic2]
Tex = ScoreBG
X = 305
Y = 95
W = 80
H = 25
Color = P1Dark
Type = Colorized

[SingP1DuetSixPTextScore]
Text = 00000
X = 320
Y = 97
Font = 0
Style = 0
Size = 24

[SingP1DuetSixPSingBar]
X = 305
Y = 120
W = 80
H = 6

#Player Two
[SingP2DuetSixPStatic]
Inherits = SingP1DuetSixPStatic
Y = 227
Color = P2Dark

[SingP2DuetSixPAvatar]
Inherits = SingP1DuetSixPAvatar
Y = 230

[SingP2DuetSixPStatic2]
Inherits = SingP1DuetSixPStatic2
Y = 222
Color = P2Dark

[SingP2DuetSixPTextScore]
Inherits = SingP1DuetSixPTextScore
Y = 224

[SingP2DuetSixPSingBar]
Inherits = SingP1DuetSixPSingBar
Y = 247

#Player Three
[SingP3DuetSixPStatic]
Inherits = SingP1DuetSixPStatic
Y = 352
Color = P3Dark

[SingP3DuetSixPAvatar]
Inherits = SingP1DuetSixPAvatar
Y = 355

[SingP3DuetSixPStatic2]
Inherits = SingP1DuetSixPStatic2
Y = 347
Color = P3Dark

[SingP3DuetSixPTextScore]
Inherits = SingP1DuetSixPTextScore
Y = 349

[SingP3DuetSixPSingBar]
Inherits = SingP1DuetSixPSingBar
Y = 372

#Player Four
[SingP4DuetSixPStatic]
Inherits = SingP1DuetSixPStatic
X = 390
Color = P4Dark

[SingP4DuetSixPAvatar]
Inherits = SingP1DuetSixPAvatar
X = 393

[SingP4DuetSixPStatic2]
Inherits = SingP1DuetSixPStatic2
X = 700
Color = P4Dark

[SingP4DuetSixPTextScore]
Inherits = SingP1DuetSixPTextScore
X = 715

[SingP4DuetSixPSingBar]
Inherits = SingP1DuetSixPSingBar
X = 700

#Player Five
[SingP5DuetSixPStatic]
Inherits = SingP2DuetSixPStatic
X = 390
Color = P5Dark

[SingP5DuetSixPAvatar]
Inherits = SingP2DuetSixPAvatar
X = 393

[SingP5DuetSixPStatic2]
Inherits = SingP2DuetSixPStatic2
X = 700
Color = P5Dark

[SingP5DuetSixPTextScore]
Inherits = SingP2DuetSixPTextScore
X = 715

[SingP5DuetSixPSingBar]
Inherits = SingP2DuetSixPSingBar
X = 700

#Player Six
[SingP6DuetSixPStatic]
Inherits = SingP3DuetSixPStatic
X = 390
Color = P6Dark

[SingP6DuetSixPAvatar]
Inherits = SingP3DuetSixPAvatar
X = 393

[SingP6DuetSixPStatic2]
Inherits = SingP3DuetSixPStatic2
X = 700
Color = P6Dark

[SingP6DuetSixPTextScore]
Inherits = SingP3DuetSixPTextScore
X = 715

[SingP6DuetSixPSingBar]
Inherits = SingP3DuetSixPSingBar
X = 700

