#################################################
##                                             ##
##          Four Player Score One Screen       ##
##                                             ##
#################################################
# P L A Y E R  O N E
[ScoreFourPTextName1]
X = 90
Y = 140
Font = 0
Style = 1
Size = 32
Align = 0
Text = P1
Color = White

# Rating
[ScoreFourPStaticRatingPicture1]
X = 315
Y = 160
H = 55
W = 55
Z = 100

[ScoreFourPTextScore1]
X = 340
Y = 220
W = 100
Color = White
Font = 0
Style = 0
Size = 24
Text = Tone Deaf
Align = 1

[ScoreFourPTextNotes1]
X = 45
Y = 180
Font = 0
Style = 0
Size = 26
Align = 0
Text = SING_NOTES
Color = White

[ScoreFourPTextNotesScore1]
X = 260
Y = 180
Font = 0
Style = 0
Size = 26
Align = 2
Text = 0000
Color = White

[ScoreFourPTextLineBonus1]
Inherits = ScoreFourPTextNotes1
Y = 205
Text = SING_PHRASE_BONUS

[ScoreFourPTextLineBonusScore1]
Inherits = ScoreFourPTextNotesScore1
Y = 205

[ScoreFourPTextGoldenNotes1]
Inherits = ScoreFourPTextNotes1
Y = 230
Text = SING_GOLDEN_NOTES

[ScoreFourPTextGoldenNotesScore1]
Inherits = ScoreFourPTextNotesScore1
Y = 230

[ScoreFourPStaticBoxDark1]
Tex = ScoreBar_box_dark
X = 20
Y = 185
W = 22
H = 20
Color = P1Dark
Type = Colorized

[ScoreFourPStaticBoxLight1]
Inherits = ScoreFourPStaticBoxDark1
Tex = ScoreBar_box_light
Y = 210
Color = P1Light

[ScoreFourPStaticBoxLightest1]
Inherits = ScoreFourPStaticBoxDark1
Tex = ScoreBar_box_lightest
Y = 235
Color = P1Lightest

[ScoreFourPTextTotal1]
X = 60
Y = 280
Font = 0
Style = 0
Size = 30
Align = 0
Text = SING_TOTAL
Color = White

[ScoreFourPTextTotalScore1]
X = 260
Y = 275
Font = 0
Style = 0
Size = 42
Align = 2
Text = 00000
Color = White

#lines
[ScoreFourPPlayer1Static1]
X = 20
Y = 180
W = 240
H = 1
Tex = ScoreLine
Type = Colorized
Color = White

[ScoreFourPPlayer1Static2]
Inherits = ScoreFourPPlayer1Static1
Y = 205

[ScoreFourPPlayer1Static3]
Inherits = ScoreFourPPlayer1Static1
Y = 230

[ScoreFourPPlayer1Static4]
Inherits = ScoreFourPPlayer1Static1
Y = 255

#ScoreBar
[ScoreFourPStaticBackLevel1]
Tex = ScoreLevel
X = 294
Y = 155
W = 95
H = 125
Color = P1Lightest
Type = Colorized
 
[ScoreFourPStaticBackLevelRound1]
Tex = ScoreLevelRound
X = 294
Y = 155
W = 95
H = 8
Color = P1Lightest
Type = Colorized

[ScoreFourPStaticLevel1]
Tex = ScoreLevel
X = 294
Y = 400
W = 95
H = 10
Color = P1Dark
Type = Colorized

[ScoreFourPStaticLevelRound1]
Tex = ScoreLevelRound
X = 294
Y = 392
W = 95
H = 8
Color = P1Dark
Type = Colorized

[ScoreFourPPlayer1Static5]
Tex = ScoreEndCap
X = 290
Y = 280
W = 110
H = 30
Z = 0.9
Color = P1Dark
Type = Colorized
Reflection = 1
ReflectionSpacing = 0

[ScoreFourPPlayer1Static6]
Tex = ScoreGlassBox
X = 290
Y = 140
W = 113
H = 140
Z = 0.89
Color = White
Type = Transparent

[ScoreFourPPlayer1Static7]
Tex = P
X = 20
Y = 280
W = 30
H = 30
Type = Colorized
Color = P1Dark
Z = 0.9
Reflection = 1
ReflectionSpacing = 4

[ScoreFourPPlayer1Text1]
Text = P1
X = 26
Y = 285
Size = 20
Font = 0
Style = 1
Type = Colorized
Color = White
Z = 1
Reflection = 1
ReflectionSpacing = 16

[ScoreFourPPlayer1Avatar]
X = 24
Y = 115
W = 51
H = 50
Z = 1

[ScoreFourPPlayer1Static8]
X = 20
Y = 110
W = 60
H = 60
Z = 0.9
Tex = AvatarFrame2
Color = P1Dark
Type = Transparent

# P L A Y E R  T W O (mirrors player 1)
[ScoreFourPTextName2]
Inherits = ScoreFourPTextName1
X = 610

# Rating
[ScoreFourPStaticRatingPicture2]
Inherits = ScoreFourPStaticRatingPicture1
X = 435

[ScoreFourPTextScore2]
Inherits = ScoreFourPTextScore1
X = 460

[ScoreFourPTextNotes2]
Inherits = ScoreFourPTextNotes1
X = 565

[ScoreFourPTextNotesScore2]
Inherits = ScoreFourPTextNotesScore1
X = 780

[ScoreFourPTextLineBonus2]
Inherits = ScoreFourPTextLineBonus1
X = 565

[ScoreFourPTextLineBonusScore2]
Inherits = ScoreFourPTextLineBonusScore1
X = 780

[ScoreFourPTextGoldenNotes2]
Inherits = ScoreFourPTextGoldenNotes1
X = 565

[ScoreFourPTextGoldenNotesScore2]
Inherits = ScoreFourPTextGoldenNotesScore1
X = 780

[ScoreFourPStaticBoxDark2]
Inherits = ScoreFourPStaticBoxDark1
X = 540
Color = P2Dark

[ScoreFourPStaticBoxLight2]
Inherits = ScoreFourPStaticBoxLight1
X = 540
Color = P2Light

[ScoreFourPStaticBoxLightest2]
Inherits = ScoreFourPStaticBoxLightest1
X = 540
Color = P2Lightest

[ScoreFourPTextTotal2]
Inherits = ScoreFourPTextTotal1
X = 580

[ScoreFourPTextTotalScore2]
Inherits = ScoreFourPTextTotalScore1
X = 780

#lines
[ScoreFourPPlayer2Static1]
Inherits = ScoreFourPPlayer1Static1
X = 540

[ScoreFourPPlayer2Static2]
Inherits = ScoreFourPPlayer1Static2
X = 540

[ScoreFourPPlayer2Static3]
Inherits = ScoreFourPPlayer1Static3
X = 540

[ScoreFourPPlayer2Static4]
Inherits = ScoreFourPPlayer1Static4
X = 540

#ScoreBar
[ScoreFourPStaticBackLevel2]
Inherits = ScoreFourPStaticBackLevel1
X = 414
Color = P2Lightest
 
[ScoreFourPStaticBackLevelRound2]
Inherits = ScoreFourPStaticBackLevelRound1
X = 414
Color = P2Lightest

[ScoreFourPStaticLevel2]
Inherits = ScoreFourPStaticLevel1
X = 414
Color = P2Dark

[ScoreFourPStaticLevelRound2]
Inherits = ScoreFourPStaticLevelRound1
X = 414
Color = P2Dark

[ScoreFourPPlayer2Static5]
Inherits = ScoreFourPPlayer1Static5
X = 410
Color = P2Dark

[ScoreFourPPlayer2Static6]
Inherits = ScoreFourPPlayer1Static6
X = 410

[ScoreFourPPlayer2Static7]
Inherits = ScoreFourPPlayer1Static7
X = 540
Color = P2Dark

[ScoreFourPPlayer2Text1]
Inherits = ScoreFourPPlayer1Text1
Text = P2
X = 546

[ScoreFourPPlayer2Avatar]
Inherits = ScoreFourPPlayer1Avatar
X = 544

[ScoreFourPPlayer2Static8]
Inherits = ScoreFourPPlayer1Static8
X = 540
Color = P2Dark

# P L A Y E R  T H R E E (mirrors player 1)
[ScoreFourPTextName3]
Inherits = ScoreFourPTextName1
Y = 360

# Rating
[ScoreFourPStaticRatingPicture3]
Inherits = ScoreFourPStaticRatingPicture1
Y = 380

[ScoreFourPTextScore3]
Inherits = ScoreFourPTextScore1
Y = 440

[ScoreFourPTextNotes3]
Inherits = ScoreFourPTextNotes1
Y = 400

[ScoreFourPTextNotesScore3]
Inherits = ScoreFourPTextNotesScore1
Y = 400

[ScoreFourPTextLineBonus3]
Inherits = ScoreFourPTextLineBonus1
Y = 425

[ScoreFourPTextLineBonusScore3]
Inherits = ScoreFourPTextLineBonusScore1
Y = 425

[ScoreFourPTextGoldenNotes3]
Inherits = ScoreFourPTextGoldenNotes1
Y = 450

[ScoreFourPTextGoldenNotesScore3]
Inherits = ScoreFourPTextGoldenNotesScore1
Y = 450

[ScoreFourPStaticBoxDark3]
Inherits = ScoreFourPStaticBoxDark1
Y = 405
Color = P3Dark

[ScoreFourPStaticBoxLight3]
Inherits = ScoreFourPStaticBoxLight1
Y = 430
Color = P3Light

[ScoreFourPStaticBoxLightest3]
Inherits = ScoreFourPStaticBoxLightest1
Y = 455
Color = P3Lightest

[ScoreFourPTextTotal3]
Inherits = ScoreFourPTextTotal1
Y = 500

[ScoreFourPTextTotalScore3]
Inherits = ScoreFourPTextTotalScore1
Y = 495

#lines
[ScoreFourPPlayer3Static1]
Inherits = ScoreFourPPlayer1Static1
Y = 400

[ScoreFourPPlayer3Static2]
Inherits = ScoreFourPPlayer1Static2
Y = 425

[ScoreFourPPlayer3Static3]
Inherits = ScoreFourPPlayer1Static3
Y = 450

[ScoreFourPPlayer3Static4]
Inherits = ScoreFourPPlayer1Static4
Y = 475

#ScoreBar
[ScoreFourPStaticBackLevel3]
Inherits = ScoreFourPStaticBackLevel1
Y = 382
H = 118
Color = P3Lightest
 
[ScoreFourPStaticBackLevelRound3]
Inherits = ScoreFourPStaticBackLevelRound1
Y = 375
H = 10
Color = P3Lightest

[ScoreFourPStaticLevel3]
Inherits = ScoreFourPStaticLevel1
X = 294
H = 8
Color = P3Dark

[ScoreFourPStaticLevelRound3]
Inherits = ScoreFourPStaticLevelRound1
X = 294
Color = P3Dark

[ScoreFourPPlayer3Static5]
Inherits = ScoreFourPPlayer1Static5
Y = 500
Color = P3Dark

[ScoreFourPPlayer3Static6]
Inherits = ScoreFourPPlayer1Static6
Y = 360

[ScoreFourPPlayer3Static7]
Inherits = ScoreFourPPlayer1Static7
Y = 500
Color = P3Dark

[ScoreFourPPlayer3Text1]
Inherits = ScoreFourPPlayer1Text1
Text = P3
Y = 505

[ScoreFourPPlayer3Avatar]
Inherits = ScoreFourPPlayer1Avatar
Y = 335

[ScoreFourPPlayer3Static8]
Inherits = ScoreFourPPlayer1Static8
Y = 330
Color = P3Dark

# P L A Y E R  F O U R (mirrors player 2)
[ScoreFourPTextName4]
Inherits = ScoreFourPTextName3
X = 610

# Rating
[ScoreFourPStaticRatingPicture4]
Inherits = ScoreFourPStaticRatingPicture3
X = 435

[ScoreFourPTextScore4]
Inherits = ScoreFourPTextScore3
X = 460

[ScoreFourPTextNotes4]
Inherits = ScoreFourPTextNotes3
X = 565

[ScoreFourPTextNotesScore4]
Inherits = ScoreFourPTextNotesScore3
X = 780

[ScoreFourPTextLineBonus4]
Inherits = ScoreFourPTextLineBonus3
X = 565

[ScoreFourPTextLineBonusScore4]
Inherits = ScoreFourPTextLineBonusScore3
X = 780

[ScoreFourPTextGoldenNotes4]
Inherits = ScoreFourPTextGoldenNotes3
X = 565

[ScoreFourPTextGoldenNotesScore4]
Inherits = ScoreFourPTextGoldenNotesScore3
X = 780

[ScoreFourPStaticBoxDark4]
Inherits = ScoreFourPStaticBoxDark3
X = 540
Color = P4Dark

[ScoreFourPStaticBoxLight4]
Inherits = ScoreFourPStaticBoxLight3
X = 540
Color = P4Light

[ScoreFourPStaticBoxLightest4]
Inherits = ScoreFourPStaticBoxLightest3
X = 540
Color = P4Lightest

[ScoreFourPTextTotal4]
Inherits = ScoreFourPTextTotal3
X = 580

[ScoreFourPTextTotalScore4]
Inherits = ScoreFourPTextTotalScore3
X = 780

#lines
[ScoreFourPPlayer4Static1]
Inherits = ScoreFourPPlayer3Static1
X = 540

[ScoreFourPPlayer4Static2]
Inherits = ScoreFourPPlayer3Static2
X = 540

[ScoreFourPPlayer4Static3]
Inherits = ScoreFourPPlayer3Static3
X = 540

[ScoreFourPPlayer4Static4]
Inherits = ScoreFourPPlayer3Static4
X = 540

#ScoreBar
[ScoreFourPStaticBackLevel4]
Inherits = ScoreFourPStaticBackLevel3
X = 414
Color = P4Lightest
 
[ScoreFourPStaticBackLevelRound4]
Inherits = ScoreFourPStaticBackLevelRound3
X = 414
Color = P4Lightest

[ScoreFourPStaticLevel4]
Inherits = ScoreFourPStaticLevel3
X = 414
Color = P4Dark

[ScoreFourPStaticLevelRound4]
Inherits = ScoreFourPStaticLevelRound3
X = 414
Color = P4Dark

[ScoreFourPPlayer4Static5]
Inherits = ScoreFourPPlayer3Static5
X = 410
Color = P4Dark

[ScoreFourPPlayer4Static6]
Inherits = ScoreFourPPlayer3Static6
X = 410

[ScoreFourPPlayer4Static7]
Inherits = ScoreFourPPlayer3Static7
X = 540
Color = P4Dark

[ScoreFourPPlayer4Text1]
Inherits = ScoreFourPPlayer3Text1
Text = P4
X = 546

[ScoreFourPPlayer4Avatar]
Inherits = ScoreFourPPlayer3Avatar
X = 544

[ScoreFourPPlayer4Static8]
Inherits = ScoreFourPPlayer3Static8
X = 540
Color = P4Dark

