########################################################################################
##### 																			   #####
#####                   				Roulette                                   #####
##### 																			   #####
########################################################################################

[SongRouletteBackground]
Tex = SongBG

[SongRouletteStaticNonParty1]
Inherits = DefaultIcon
Tex = SongCD

[SongRouletteTextCat]
X = 72
Y = 60
Color = White
Font = 0
Style = 0
Size = 30
Align = 0
Text = SING_SONG_SELECTION_DESC

[SongRouletteStatic1]
Inherits = DefaultBar1
Z = 0.4

[SongRouletteStatic2]
Inherits = DefaultBar2
Z = 0.951

[SongRouletteCover]
X = 300
Y = 120
W = 200
H = 200
Reflections = 1

[SongRouletteEqualizer]
Visible = 1
Direction = 1
Color = White
Alpha = 1
X = 265
Y = 476
PieceW = 4
PieceH = 4
Space = 1
Bands = 5
Length = 15
Reflection = 1
ReflectionSpacing = 2

[SongRouletteMedleyIcon]
X = 335
Y = 445
W = 24
H = 24
Z = 0.95
Color = White
Tex = icon_song_medley
Type = Transparent
Reflection = 1
ReflectionSpacing = 22

[SongRouletteCalculatedMedleyIcon]
Inherits = SongRouletteMedleyIcon
Tex = icon_song_calcmedley

[SongRouletteVideoIcon]
Inherits = SongRouletteMedleyIcon
X = 310
Tex = icon_song_video

[SongRouletteDuetIcon]
Inherits = SongRouletteMedleyIcon
X = 335
Tex = icon_song_duet

[SongRouletteRapIcon]
Inherits = SongRouletteDuetIcon
Tex = icon_song_rap

[SongRouletteRapToFreestyleIcon]
Inherits = SongRouletteDuetIcon
Tex = icon_song_rap_to_freestyle

[SongRouletteStatic3]
X = 278
Y = 120
W = 244
H = 200
Z = 0.95
Color = ColorLight
Tex = SongSelection1
Type = Colorized

[SongRouletteStatic4]
X = 300
Y = 320
W = 200
H = 160
Z = 0.95
Color = ColorLight
Tex = SongSelection2
Type = Colorized
Reflection = 1
ReflectionSpacing = 2

[SongRouletteTextArtist]
X = 400
Y = 328
W = 190
H = 48
Color = White
Font = 0
Style = 1
Size = 24
Align = 1
Text =

[SongRouletteTextTitle]
Inherits = SongRouletteTextArtist
Y = 394
H = 72
Style = 0

[SongRouletteTextNumber]
X = 492
Y = 457
Z = 0.95
Color = White
Size = 14
Align = 2
Reflection = 1
ReflectionSpacing = 21

[SongRouletteTextYear]
X = 400
Y = 447
Z = 0.95
Color = White
Size = 20
Align = 1

########################################
####      SCREEN SONGS SCORES      #####
######################################## 

[SongRouletteTextScore]
X = 530
Y = 420
Color = ColorLight
Font = 0
Style = 0
Size = 24
Align = 0

[SongRouletteTextMaxScore]
X = 530
Y = 450
Color = White
Font = 0
Style = 0
Size = 22
Align = 0
Text =SONG_SCORE_MAX

[SongRouletteTextMediaScore]
Inherits = SongRouletteTextMaxScore
Y = 490
Text =SONG_SCORE_MEDIA

[SongRouletteTextMaxScore2]
X = 670
Y = 450
Color = White
Font = 0
Style = 0
Size = 22
Align = 2

[SongRouletteTextMediaScore2]
Inherits = SongRouletteTextMaxScore2
Y = 490

[SongRouletteTextScoreUser]
X = 670
Y = 468
Color = ColorLight
Font = 0
Style = 0
Size = 20
Align = 2

[SongRouletteTextMaxScoreLocal]
X = 680
Y = 450
Color = White
Font = 0
Style = 0
Size = 22
Align = 0

[SongRouletteTextMediaScoreLocal]
Inherits = SongRouletteTextMaxScoreLocal
Y = 490

[SongRouletteTextScoreUserLocal]
X = 680
Y = 468
Color = ColorLight
Font = 0
Style = 0
Size = 20
Align = 0

#Variable statics and texts for song-screen in sing- and partymode
# There can be an unlimited Number of Statics and Texts, As long
# as the numbers are in order.
# Statics that are shown in PartyMode Only are Named_
#        SongStaticParty[No]
# Texts that are shown in PartyMode Only are Named_
#        SongTextParty[No]
# Statics that are shown in Normal Mode Only are Named_
#        SongStaticNonParty[No]
# Texts that are shown in Normal Mode Only are Named_
#        SongTextNonParty[No]
#Here are the ones for singmode

[SongRouletteTextNonParty1]
X = 70
Y = 5
Color = White
Font = 0
Style = 0
Size = 60
Text = SING_SONG_SELECTION
Align = 0

# NAVBAR #########################
# Jump to a letter with [ALT] + [A..Z]
[SongRouletteStaticNonParty2]
Inherits = DefaultLegendStatic
Z = 0.952
Tex = ButtonAlt

[SongRouletteTextNonParty2]
Inherits = DefaultLegendText
X = 292
Z = 0.952
Text = +

[SongRouletteStaticNonParty3]
Inherits = DefaultLegendStatic
X = 300
Z = 0.952
Tex = ButtonAZ

[SongRouletteTextNonParty3]
Inherits = DefaultLegendText
X = 340
Z = 0.952
Text = SING_SONG_SELECTION_GOTO

# Menu opens with [M]
[SongRouletteStaticNonParty4]
Inherits = DefaultLegendStatic
X = 425
Z = 0.952
Tex = ButtonM

[SongRouletteTextNonParty4]
Inherits = DefaultLegendText
X = 465
Z = 0.952
Text = SING_SONG_SELECTION_MENU

# The so famous search, shown with [J]
[SongRouletteStaticNonParty5]
Inherits = DefaultLegendStatic
X = 515
Z = 0.952
Tex = ButtonJ

[SongRouletteTextNonParty5]
Inherits = DefaultLegendText
X = 555
Z = 0.952
Text = SONG_JUMPTO_DESC

# [P]laylist
[SongRouletteStaticNonParty6]
Inherits = DefaultLegendStatic
X = 680
Z = 0.952
Tex = ButtonP

[SongRouletteTextNonParty6]
Inherits = DefaultLegendText
X = 720
Z = 0.952
Text = SING_SONG_SELECTION_PLAYLIST

[SongRouletteTextNonParty7]
Inherits = DefaultTextWhereAmI
Text = SING_SONG_SELECTION_WHEREAMI

#and these are the ones for partymode
[SongRouletteStaticParty1]
Inherits = DefaultPartyIcon

# NAVBAR for party
# enter a number
[SongRouletteStaticParty2]
Inherits = DefaultLegendStatic
Z = 0.952
Tex = Button13

[SongRouletteTextParty3]
Inherits = DefaultLegendText
Z = 0.952
Text = SONG_MENU_NAME_PARTY_JOKER

# menu
[SongRouletteStaticParty3]
Inherits = DefaultLegendStatic
X = 400
Z = 0.952
Tex = ButtonM

[SongRouletteTextParty4]
Inherits = DefaultLegendText
X = 440
Z = 0.952
Text = PARTY_SONG_MENU

[SongRouletteStaticParty4]
Inherits = DefaultLegendStatic
X = 540
Z = 0.952
Tex = ButtonEnter

[SongRouletteTextParty5]
Inherits = DefaultLegendText
X = 580
Text = PARTY_SONG_LEGEND_CONTINUE

#Texts for Party Mode
[SongRouletteTextParty1]
Inherits = DefaultPartyTitleText

[SongRouletteTextParty2]
Inherits = DefaultTextWhereAmI
Text = PARTY_SONG_WHEREAMI
#variable statics end

# Jokers, 5 for each team, only shown in party Mode
[SongRouletteStaticTeam1Joker1]
Tex = Joker
X = 505
Y = 400
W = 40
H = 40
Z = 0.98
Color = P1Dark
Type = Colorized

[SongRouletteStaticTeam1Joker2]
Inherits = SongRouletteStaticTeam1Joker1
X = 555

[SongRouletteStaticTeam1Joker3]
Inherits = SongRouletteStaticTeam1Joker1
X = 605

[SongRouletteStaticTeam1Joker4]
Inherits = SongRouletteStaticTeam1Joker1
X = 655

[SongRouletteStaticTeam1Joker5]
Inherits = SongRouletteStaticTeam1Joker1
X = 705

[SongRouletteStaticTeam2Joker1]
Inherits = SongRouletteStaticTeam1Joker1
Y = 450
Color = P2Dark

[SongRouletteStaticTeam2Joker2]
Inherits = SongRouletteStaticTeam2Joker1
X = 555

[SongRouletteStaticTeam2Joker3]
Inherits = SongRouletteStaticTeam2Joker1
X = 605

[SongRouletteStaticTeam2Joker4]
Inherits = SongRouletteStaticTeam2Joker1
X = 655

[SongRouletteStaticTeam2Joker5]
Inherits = SongRouletteStaticTeam2Joker1
X = 705

[SongRouletteStaticTeam3Joker1]
Inherits = SongRouletteStaticTeam1Joker1
Y = 500
Color = P3Dark

[SongRouletteStaticTeam3Joker2]
Inherits = SongRouletteStaticTeam3Joker1
X = 555

[SongRouletteStaticTeam3Joker3]
Inherits = SongRouletteStaticTeam3Joker1
X = 605

[SongRouletteStaticTeam3Joker4]
Inherits = SongRouletteStaticTeam3Joker1
X = 655

[SongRouletteStaticTeam3Joker5]
Inherits = SongRouletteStaticTeam3Joker1
X = 705

[SongRouletteInfoMessageBG]
Tex = SongMessage
X = 250
Y = 90
W = 300
H = 25
Z = 0.98
Color = ColorDark
Type = Transparent

[SongRouletteInfoMessageText]
X = 400
Y = 94
Color = White
Font = 0
Style = 1
Size = 20
Align = 1

#############################
##                         ## 
##     Medley Playlist     ##
##                         ##
#############################

[SongRouletteTextMedleyNumber1]
X=25
Y=375
Color=White
Font=1
Size=20
Align=1

[SongRouletteTextMedleyArtist1]
X=50
Y=366
Color=ColorDark
Font=0
Size=20
Align=0

[SongRouletteTextMedleyTitle1]
X=50
Y=383
Color=White
Font=0
Size=20
Align=0

[SongRouletteTextMedleyNumber2]
Inherits = SongRouletteTextMedleyNumber1
Y=420

[SongRouletteTextMedleyArtist2]
Inherits = SongRouletteTextMedleyArtist1
Y=411

[SongRouletteTextMedleyTitle2]
Inherits = SongRouletteTextMedleyTitle1
Y=428

[SongRouletteTextMedleyNumber3]
Inherits = SongRouletteTextMedleyNumber1
Y=465

[SongRouletteTextMedleyArtist3]
Inherits = SongRouletteTextMedleyArtist1
Y=454

[SongRouletteTextMedleyTitle3]
Inherits = SongRouletteTextMedleyTitle1
Y=471

[SongRouletteTextMedleyNumber4]
Inherits = SongRouletteTextMedleyNumber1
Y=510

[SongRouletteTextMedleyArtist4]
Inherits = SongRouletteTextMedleyArtist1
Y=501

[SongRouletteTextMedleyTitle4]
Inherits = SongRouletteTextMedleyTitle1
Y=518

[SongRouletteStaticMedley1]
Tex = PlayerNumberBox
X = 10
Y = 370
W = 30
H = 30
Color = ColorDark
Type = Colorized

[SongRouletteStaticMedley2]
Inherits = SongRouletteStaticMedley1
Y = 415

[SongRouletteStaticMedley3]
Inherits = SongRouletteStaticMedley1
Y = 460

[SongRouletteStaticMedley4]
Inherits = SongRouletteStaticMedley1
Y = 505

