########################################################################################
##### 																			   #####
#####                   			   Chessboard                                  #####
##### 																			   #####
########################################################################################

[SongChessboardBackground]
Tex = SongBG

[SongChessboardStaticNonParty1]
Inherits = SongRouletteStaticNonParty1

[SongChessboardTextCat]
Inherits = SongRouletteTextCat

[SongChessboardStatic1]
Inherits = DefaultBar1
Z = 0.4

[SongChessboardStatic2]
Inherits = DefaultBar2
Z = 0.951

[SongChessboardCover]
X = 270
Y = 100
W = 100
H = 100
SelectX = 25
SelectY = 120
SelectW = 200
SelectH = 200
ZoomThumbW = 120
ZoomThumbH = 120
ZoomThumbStyle = 0
Rows = 3
Cols = 5
Padding = 2
Reflections = 0
Tex = PlayerNumberBox

[SongChessboardEqualizer]
Visible = 1
Direction = 1
Color = White
Alpha = 1
X = 235
Y = 476
PieceW = 4
PieceH = 4
Space = 1
Bands = 5
Length = 15
Reflection = 1
ReflectionSpacing = 2

[SongChessboardMedleyIcon]
X = 60
Y = 445
W = 24
H = 24
Z = 0.95
Color = White
Tex = icon_song_medley
Type = Transparent
Reflection = 1
ReflectionSpacing = 22

[SongChessboardCalculatedMedleyIcon]
Inherits = SongChessboardMedleyIcon

[SongChessboardVideoIcon]
Inherits = SongChessboardMedleyIcon
X = 35
Tex = icon_song_video

[SongChessboardDuetIcon]
Inherits = SongChessboardMedleyIcon
Tex = icon_song_duet

[SongChessboardRapIcon]
Inherits = SongChessboardMedleyIcon
Tex = icon_song_rap

[SongChessboardRapToFreestyleIcon]
Inherits = SongChessboardMedleyIcon
Tex = icon_song_rap_to_freestyle

[SongChessboardStatic3]
X = 25
Y = 320
W = 200
H = 160
Z = 0.95
Color = ColorLight
Tex = SongSelection2
Type = Colorized
Reflection = 1
ReflectionSpacing = 2

[SongChessboardTextArtist]
X = 125
Y = 328
W = 190
Color = White
Font = 0
Style = 1
Size = 24
Align = 1
Text =

[SongChessboardTextTitle]
Inherits = SongChessboardTextArtist
Y = 394
Style = 0

[SongChessboardTextNumber]
X = 217
Y = 457
Z = 0.95
Color = White
Size = 14
Align = 2
Reflection = 1
ReflectionSpacing = 21

[SongChessboardTextYear]
X = 125
Y = 447
Z = 0.95
Color = White
Size = 20
Align = 1

[SongChessboardTextScore]
X = 270
Y = 435
Color = ColorLight
Font = 0
Style = 0
Size = 24
Align = 0

[SongChessboardTextMaxScore]
X = 270
Y = 465
Color = White
Font = 0
Style = 0
Size = 22
Align = 0
Text =SONG_SCORE_MAX

[SongChessboardTextMediaScore]
Inherits = SongChessboardTextMaxScore
Y = 505
Text =SONG_SCORE_MEDIA

[SongChessboardTextMaxScore2]
X = 410
Y = 465
Color = White
Font = 0
Style = 0
Size = 22
Align = 2

[SongChessboardTextMediaScore2]
Inherits = SongChessboardTextMaxScore2
Y = 505

[SongChessboardTextScoreUser]
X = 410
Y = 483
Color = ColorLight
Font = 0
Style = 0
Size = 20
Align = 2

[SongChessboardTextMaxScoreLocal]
X = 420
Y = 465
Color = White
Font = 0
Style = 0
Size = 22
Align = 0

[SongChessboardTextMediaScoreLocal]
Inherits = SongChessboardTextMaxScoreLocal
Y = 505

[SongChessboardTextScoreUserLocal]
X = 420
Y = 483
Color = ColorLight
Font = 0
Style = 0
Size = 20
Align = 0

[SongChessboardTextNonParty1]
Inherits = SongRouletteTextNonParty1

[SongChessboardStaticNonParty2]
Inherits = SongRouletteStaticNonParty2

[SongChessboardTextNonParty2]
Inherits = SongRouletteTextNonParty2

[SongChessboardStaticNonParty3]
Inherits = SongRouletteStaticNonParty3

[SongChessboardTextNonParty3]
Inherits = SongRouletteTextNonParty3

[SongChessboardStaticNonParty4]
Inherits = SongRouletteStaticNonParty4

[SongChessboardTextNonParty4]
Inherits = SongRouletteTextNonParty4

[SongChessboardStaticNonParty5]
Inherits = SongRouletteStaticNonParty5

[SongChessboardTextNonParty5]
Inherits = SongRouletteTextNonParty5

[SongChessboardStaticNonParty6]
Inherits = SongRouletteStaticNonParty6

[SongChessboardTextNonParty6]
Inherits = SongRouletteTextNonParty6

[SongChessboardStaticParty1]
Inherits = DefaultPartyIcon

[SongChessboardStaticParty2]
Inherits = SongRouletteStaticParty2

[SongChessboardTextParty3]
Inherits = DefaultLegendText
Z = 0.952
Text = SONG_MENU_NAME_PARTY_JOKER

[SongChessboardStaticParty3]
Inherits = SongRouletteStaticParty3

[SongChessboardTextParty4]
Inherits = SongRouletteTextParty4

[SongChessboardStaticParty4]
Inherits = SongRouletteStaticParty4

[SongChessboardTextParty5]
Inherits = SongRouletteTextParty5

[SongChessboardTextParty1]
Inherits = DefaultPartyTitleText

[SongChessboardTextParty2]
Inherits = DefaultTextWhereAmI
Text = PARTY_SONG_WHEREAMI

[SongChessboardStaticTeam1Joker1]
Inherits = SongRouletteStaticTeam1Joker1
X = 505
Y = 420
W = 30
H = 30

[SongChessboardStaticTeam1Joker2]
Inherits = SongChessboardStaticTeam1Joker1
X = 555

[SongChessboardStaticTeam1Joker3]
Inherits = SongChessboardStaticTeam1Joker1
X = 605

[SongChessboardStaticTeam1Joker4]
Inherits = SongChessboardStaticTeam1Joker1
X = 655

[SongChessboardStaticTeam1Joker5]
Inherits = SongChessboardStaticTeam1Joker1
X = 705

[SongChessboardStaticTeam2Joker1]
Inherits = SongChessboardStaticTeam1Joker1
Y = 460
Color = P2Dark

[SongChessboardStaticTeam2Joker2]
Inherits = SongChessboardStaticTeam2Joker1
X = 555

[SongChessboardStaticTeam2Joker3]
Inherits = SongChessboardStaticTeam2Joker1
X = 605

[SongChessboardStaticTeam2Joker4]
Inherits = SongChessboardStaticTeam2Joker1
X = 655

[SongChessboardStaticTeam2Joker5]
Inherits = SongChessboardStaticTeam2Joker1
X = 705

[SongChessboardStaticTeam3Joker1]
Inherits = SongChessboardStaticTeam2Joker1
Y = 500
Color = P3Dark

[SongChessboardStaticTeam3Joker2]
Inherits = SongChessboardStaticTeam3Joker1
X = 555

[SongChessboardStaticTeam3Joker3]
Inherits = SongChessboardStaticTeam3Joker1
X = 605

[SongChessboardStaticTeam3Joker4]
Inherits = SongChessboardStaticTeam3Joker1
X = 655

[SongChessboardStaticTeam3Joker5]
Inherits = SongChessboardStaticTeam3Joker1
X = 705

[SongChessboardInfoMessageBG]
Inherits = SongRouletteInfoMessageBG

[SongChessboardInfoMessageText]
Inherits = SongRouletteInfoMessageText

#############################
##                         ## 
##     Medley Playlist     ##
##                         ##
#############################

[SongChessboardTextMedleyMax]
N = 3

[SongChessboardTextMedleyNumber1]
X=530
Y=420 
Color=White
Font=1
Size=20
Align=1

[SongChessboardTextMedleyArtist1]
X=555
Y=411
Color=ColorDark
Font=0
Size=20
Align=0

[SongChessboardTextMedleyTitle1]
X=555
Y=428
Color=White
Font=0
Size=20
Align=0

[SongChessboardTextMedleyNumber2]
Inherits = SongChessboardTextMedleyNumber1
Y=465

[SongChessboardTextMedleyArtist2]
Inherits = SongChessboardTextMedleyArtist1
Y=456

[SongChessboardTextMedleyTitle2]
Inherits = SongChessboardTextMedleyTitle1
Y=473

[SongChessboardTextMedleyNumber3]
Inherits = SongChessboardTextMedleyNumber1
Y=510

[SongChessboardTextMedleyArtist3]
Inherits = SongChessboardTextMedleyArtist1
Y=501

[SongChessboardTextMedleyTitle3]
Inherits = SongChessboardTextMedleyTitle1
Y=518

[SongChessboardStaticMedley1]
Tex = PlayerNumberBox
X = 515
Y = 415
W = 30
H = 30
Color = ColorDark
Type = Colorized

[SongChessboardStaticMedley2]
Inherits = SongChessboardStaticMedley1
Y = 460

[SongChessboardStaticMedley3]
Inherits = SongChessboardStaticMedley1
Y = 505

