########################################################################################
##### 																			   #####
#####                   			   Carousel                                    #####
##### 																			   #####
########################################################################################

[SongCarouselBackground]
Tex = SongBG

[SongCarouselStaticNonParty1]
Inherits = SongRouletteStaticNonParty1

[SongCarouselTextCat]
Inherits = SongRouletteTextCat

[SongCarouselStatic1]
Inherits = DefaultBar1
Z = 0.4

[SongCarouselStatic2]
Inherits = DefaultBar2
Z = 0.951

[SongCarouselCover]
Inherits = SongRouletteCover
Padding = 60
Reflections = 1

[SongCarouselEqualizer]
Inherits = SongRouletteEqualizer

[SongCarouselMedleyIcon]
Inherits = SongRouletteMedleyIcon

[SongCarouselCalculatedMedleyIcon]
Inherits = SongRouletteCalculatedMedleyIcon

[SongCarouselVideoIcon]
Inherits = SongRouletteVideoIcon

[SongCarouselDuetIcon]
Inherits = SongRouletteDuetIcon

[SongCarouselRapIcon]
Inherits = SongRouletteRapIcon

[SongCarouselRapToFreestyleIcon]
Inherits = SongRouletteRapToFreestyleIcon

[SongCarouselStatic3]
Inherits = SongRouletteStatic3

[SongCarouselStatic4]
Inherits = SongRouletteStatic4

[SongCarouselTextArtist]
Inherits = SongRouletteTextArtist

[SongCarouselTextTitle]
Inherits = SongRouletteTextTitle

[SongCarouselTextNumber]
Inherits = SongRouletteTextNumber

[SongCarouselTextYear]
Inherits = SongRouletteTextYear

[SongCarouselTextScore]
Inherits = SongRouletteTextScore

[SongCarouselTextMaxScore]
Inherits = SongRouletteTextMaxScore

[SongCarouselTextMediaScore]
Inherits = SongRouletteTextMediaScore

[SongCarouselTextMaxScore2]
Inherits = SongRouletteTextMaxScore2

[SongCarouselTextMediaScore2]
Inherits = SongRouletteTextMediaScore2

[SongCarouselTextScoreUser]
Inherits = SongRouletteTextScoreUser

[SongCarouselTextMaxScoreLocal]
Inherits = SongRouletteTextMaxScoreLocal

[SongCarouselTextMediaScoreLocal]
Inherits = SongRouletteTextMediaScoreLocal

[SongCarouselTextScoreUserLocal]
Inherits = SongRouletteTextScoreUserLocal

[SongCarouselTextNonParty1]
Inherits = SongRouletteTextNonParty1

[SongCarouselStaticNonParty2]
Inherits = SongRouletteStaticNonParty2

[SongCarouselTextNonParty2]
Inherits = SongRouletteTextNonParty2

[SongCarouselStaticNonParty3]
Inherits = SongRouletteStaticNonParty3

[SongCarouselTextNonParty3]
Inherits = SongRouletteTextNonParty3

[SongCarouselStaticNonParty4]
Inherits = SongRouletteStaticNonParty4

[SongCarouselTextNonParty4]
Inherits = SongRouletteTextNonParty4

[SongCarouselStaticNonParty5]
Inherits = SongRouletteStaticNonParty5

[SongCarouselTextNonParty5]
Inherits = SongRouletteTextNonParty5

[SongCarouselStaticNonParty6]
Inherits = SongRouletteStaticNonParty6

[SongCarouselTextNonParty6]
Inherits = SongRouletteTextNonParty6

[SongCarouselStaticParty1]
Inherits = DefaultPartyIcon

[SongCarouselStaticParty2]
Inherits = SongRouletteStaticParty2

[SongCarouselTextParty3]
Inherits = DefaultLegendText
Z = 0.952
Text = SONG_MENU_NAME_PARTY_JOKER

[SongCarouselStaticParty3]
Inherits = SongRouletteStaticParty3

[SongCarouselTextParty4]
Inherits = SongRouletteTextParty4

[SongCarouselStaticParty4]
Inherits = SongRouletteStaticParty4

[SongCarouselTextParty5]
Inherits = SongRouletteTextParty5

[SongCarouselTextParty1]
Inherits = DefaultPartyTitleText

[SongCarouselTextParty2]
Inherits = DefaultTextWhereAmI
Text = PARTY_SONG_WHEREAMI

[SongCarouselStaticTeam1Joker1]
Inherits = SongRouletteStaticTeam1Joker1

[SongCarouselStaticTeam1Joker2]
Inherits = SongRouletteStaticTeam1Joker2

[SongCarouselStaticTeam1Joker3]
Inherits = SongRouletteStaticTeam1Joker3

[SongCarouselStaticTeam1Joker4]
Inherits = SongRouletteStaticTeam1Joker4

[SongCarouselStaticTeam1Joker5]
Inherits = SongRouletteStaticTeam1Joker5

[SongCarouselStaticTeam2Joker1]
Inherits = SongRouletteStaticTeam2Joker1

[SongCarouselStaticTeam2Joker2]
Inherits = SongRouletteStaticTeam2Joker2

[SongCarouselStaticTeam2Joker3]
Inherits = SongRouletteStaticTeam2Joker3

[SongCarouselStaticTeam2Joker4]
Inherits = SongRouletteStaticTeam2Joker4

[SongCarouselStaticTeam2Joker5]
Inherits = SongRouletteStaticTeam2Joker5

[SongCarouselStaticTeam3Joker1]
Inherits = SongRouletteStaticTeam3Joker1

[SongCarouselStaticTeam3Joker2]
Inherits = SongRouletteStaticTeam3Joker2

[SongCarouselStaticTeam3Joker3]
Inherits = SongRouletteStaticTeam3Joker3

[SongCarouselStaticTeam3Joker4]
Inherits = SongRouletteStaticTeam3Joker4

[SongCarouselStaticTeam3Joker5]
Inherits = SongRouletteStaticTeam3Joker5

[SongCarouselInfoMessageBG]
Inherits = SongRouletteInfoMessageBG

[SongCarouselInfoMessageText]
Inherits = SongRouletteInfoMessageText

[SongCarouselTextMedleyNumber1]
Inherits = SongRouletteTextMedleyNumber1

[SongCarouselTextMedleyArtist1]
Inherits = SongRouletteTextMedleyArtist1

[SongCarouselTextMedleyTitle1]
Inherits = SongRouletteTextMedleyTitle1

[SongCarouselTextMedleyNumber2]
Inherits = SongRouletteTextMedleyNumber2

[SongCarouselTextMedleyArtist2]
Inherits = SongRouletteTextMedleyArtist2

[SongCarouselTextMedleyTitle2]
Inherits = SongRouletteTextMedleyTitle2

[SongCarouselTextMedleyNumber3]
Inherits = SongRouletteTextMedleyNumber3

[SongCarouselTextMedleyArtist3]
Inherits = SongRouletteTextMedleyArtist3

[SongCarouselTextMedleyTitle3]
Inherits = SongRouletteTextMedleyTitle3

[SongCarouselTextMedleyNumber4]
Inherits = SongRouletteTextMedleyNumber4

[SongCarouselTextMedleyArtist4]
Inherits = SongRouletteTextMedleyArtist4

[SongCarouselTextMedleyTitle4]
Inherits = SongRouletteTextMedleyTitle4

[SongCarouselStaticMedley1]
Inherits = SongRouletteStaticMedley1

[SongCarouselStaticMedley2]
Inherits = SongRouletteStaticMedley2

[SongCarouselStaticMedley3]
Inherits = SongRouletteStaticMedley3

[SongCarouselStaticMedley4]
Inherits = SongRouletteStaticMedley4

