########################################################################################
##### 																			   #####
#####                   			SlotMachine                                    #####
##### 																			   #####
########################################################################################

[SongSlotMachineBackground]
Tex = SongBG

[SongSlotMachineStaticNonParty1]
Inherits = SongRouletteStaticNonParty1

[SongSlotMachineTextCat]
Inherits = SongRouletteTextCat

[SongSlotMachineStatic1]
Inherits = DefaultBar1
Z = 0.4

[SongSlotMachineStatic2]
Inherits = DefaultBar2
Z = 0.951

[SongSlotMachineCover]
X = 60
Y = 190
W = 325
H = 200

[SongSlotMachineEqualizer]
Visible = 1
Direction = 1
Color = White
Alpha = 1
X = 580
Y = 380
PieceW = 3
PieceH = 3
Space = 1
Bands = 30
Length = 15

[SongSlotMachineMedleyIcon]
X = 315
Y = 350
W = 32
H = 30
Z = 0.95
Color = White
Tex = icon_song_medley
Type = Transparent

[SongSlotMachineCalculatedMedleyIcon]
Inherits = SongSlotMachineMedleyIcon
Tex = icon_song_calcmedley

[SongSlotMachineVideoIcon]
Inherits = SongSlotMachineMedleyIcon
X = 280
Tex = icon_song_video

[SongSlotMachineDuetIcon]
Inherits = SongSlotMachineMedleyIcon
Tex = icon_song_duet

[SongSlotMachineRapIcon]
Inherits = SongSlotMachineMedleyIcon
Tex = icon_song_rap

[SongSlotMachineRapToFreestyleIcon]
Inherits = SongSlotMachineMedleyIcon
Tex = icon_song_rap_to_freestyle

[SongSlotMachineStatic3]
X = 260
Y = 190
W = 460
H = 200
Z = 0.95
Color = ColorLight
Tex = SongSelection3
Type = Colorized

[SongSlotMachineTextArtist]
X = 280
Y = 210
W = 420
Color = White
Font = 0
Style = 1
Size = 40
Align = 0
Text =

[SongSlotMachineTextTitle]
Inherits = SongSlotMachineTextArtist
Y = 280
Style = 0
Size = 36

[SongSlotMachineTextNumber]
X = 705
Y = 200
Z = 0.95
Color = White
Size = 14
Align = 2

[SongSlotMachineTextYear]
X = 460
Y = 350
Z = 0.95
Color = White
Size = 28
Align = 1

[SongSlotMachineTextScore]
X = 290
Y = 420
Color = ColorLight
Font = 0
Style = 0
Size = 24
Align = 0

[SongSlotMachineTextMaxScore]
X = 290
Y = 450
Color = White
Font = 0
Style = 0
Size = 22
Align = 0
Text =SONG_SCORE_MAX

[SongSlotMachineTextMediaScore]
Inherits = SongSlotMachineTextMaxScore
Y = 490
Text =SONG_SCORE_MEDIA

[SongSlotMachineTextMaxScore2]
X = 430
Y = 450
Color = White
Font = 0
Style = 0
Size = 22
Align = 2

[SongSlotMachineTextMediaScore2]
Inherits = SongSlotMachineTextMaxScore2
Y = 490

[SongSlotMachineTextScoreUser]
X = 430
Y = 468
Color = ColorLight
Font = 0
Style = 0
Size = 20
Align = 2

[SongSlotMachineTextMaxScoreLocal]
X = 440
Y = 450
Color = White
Font = 0
Style = 0
Size = 22
Align = 0

[SongSlotMachineTextMediaScoreLocal]
Inherits = SongSlotMachineTextMaxScoreLocal
Y = 490

[SongSlotMachineTextScoreUserLocal]
X = 440
Y = 468
Color = ColorLight
Font = 0
Style = 0
Size = 20
Align = 0

[SongSlotMachineTextNonParty1]
Inherits = SongRouletteTextNonParty1

[SongSlotMachineStaticNonParty2]
Inherits = SongRouletteStaticNonParty2

[SongSlotMachineTextNonParty2]
Inherits = SongRouletteTextNonParty2

[SongSlotMachineStaticNonParty3]
Inherits = SongRouletteStaticNonParty3

[SongSlotMachineTextNonParty3]
Inherits = SongRouletteTextNonParty3

[SongSlotMachineStaticNonParty4]
Inherits = SongRouletteStaticNonParty4

[SongSlotMachineTextNonParty4]
Inherits = SongRouletteTextNonParty4

[SongSlotMachineStaticNonParty5]
Inherits = SongRouletteStaticNonParty5

[SongSlotMachineTextNonParty5]
Inherits = SongRouletteTextNonParty5

[SongSlotMachineStaticNonParty6]
Inherits = SongRouletteStaticNonParty6

[SongSlotMachineTextNonParty6]
Inherits = SongRouletteTextNonParty6

[SongSlotMachineStaticParty1]
Inherits = DefaultPartyIcon

[SongSlotMachineStaticParty2]
Inherits = SongRouletteStaticParty2

[SongSlotMachineTextParty3]
Inherits = DefaultLegendText
Z = 0.952
Text = SONG_MENU_NAME_PARTY_JOKER

[SongSlotMachineStaticParty3]
Inherits = SongRouletteStaticParty3

[SongSlotMachineTextParty4]
Inherits = SongRouletteTextParty4

[SongSlotMachineStaticParty4]
Inherits = SongRouletteStaticParty4

[SongSlotMachineTextParty5]
Inherits = SongRouletteTextParty5

[SongSlotMachineTextParty1]
Inherits = DefaultPartyTitleText

[SongSlotMachineTextParty2]
Inherits = DefaultTextWhereAmI
Text = PARTY_SONG_WHEREAMI

[SongSlotMachineStaticTeam1Joker1]
Inherits = SongRouletteStaticTeam1Joker1

[SongSlotMachineStaticTeam1Joker2]
Inherits = SongRouletteStaticTeam1Joker2

[SongSlotMachineStaticTeam1Joker3]
Inherits = SongRouletteStaticTeam1Joker3

[SongSlotMachineStaticTeam1Joker4]
Inherits = SongRouletteStaticTeam1Joker4

[SongSlotMachineStaticTeam1Joker5]
Inherits = SongRouletteStaticTeam1Joker5

[SongSlotMachineStaticTeam2Joker1]
Inherits = SongRouletteStaticTeam2Joker1

[SongSlotMachineStaticTeam2Joker2]
Inherits = SongRouletteStaticTeam2Joker2

[SongSlotMachineStaticTeam2Joker3]
Inherits = SongRouletteStaticTeam2Joker3

[SongSlotMachineStaticTeam2Joker4]
Inherits = SongRouletteStaticTeam2Joker4

[SongSlotMachineStaticTeam2Joker5]
Inherits = SongRouletteStaticTeam2Joker5

[SongSlotMachineStaticTeam3Joker1]
Inherits = SongRouletteStaticTeam3Joker1

[SongSlotMachineStaticTeam3Joker2]
Inherits = SongRouletteStaticTeam3Joker2

[SongSlotMachineStaticTeam3Joker3]
Inherits = SongRouletteStaticTeam3Joker3

[SongSlotMachineStaticTeam3Joker4]
Inherits = SongRouletteStaticTeam3Joker4

[SongSlotMachineStaticTeam3Joker5]
Inherits = SongRouletteStaticTeam3Joker5

[SongSlotMachineInfoMessageBG]
Inherits = SongRouletteInfoMessageBG

[SongSlotMachineInfoMessageText]
Inherits = SongRouletteInfoMessageText

[SongSlotMachineTextMedleyNumber1]
X=565
Y=415
Color=White
Font=1
Size=20
Align=1

[SongSlotMachineTextMedleyArtist1]
X=590
Y=406
Color=ColorDark
Font=0
Size=20
Align=0

[SongSlotMachineTextMedleyTitle1]
X=590
Y=423
Color=White
Font=0
Size=20
Align=0

[SongSlotMachineTextMedleyNumber2]
Inherits = SongSlotMachineTextMedleyNumber1
Y=460

[SongSlotMachineTextMedleyArtist2]
Inherits = SongSlotMachineTextMedleyArtist1
Y=451

[SongSlotMachineTextMedleyTitle2]
Inherits = SongSlotMachineTextMedleyTitle1
Y=468

[SongSlotMachineTextMedleyNumber3]
Inherits = SongSlotMachineTextMedleyNumber1
Y=505

[SongSlotMachineTextMedleyArtist3]
Inherits = SongSlotMachineTextMedleyArtist1
Y=494

[SongSlotMachineTextMedleyTitle3]
Inherits = SongSlotMachineTextMedleyTitle1
Y=511

[SongSlotMachineStaticMedley1]
Tex = PlayerNumberBox
X = 550
Y = 410
W = 30
H = 30
Color = ColorDark
Type = Colorized

[SongSlotMachineStaticMedley2]
Inherits = SongSlotMachineStaticMedley1
Y = 455

[SongSlotMachineStaticMedley3]
Inherits = SongSlotMachineStaticMedley1
Y = 500

