########################################################################################
##### 																			   #####
#####                   		   	   Slide                                       #####
##### 																			   #####
########################################################################################

[SongSlideBackground]
Tex = SongBG

[SongSlideStaticNonParty1]
Inherits = SongRouletteStaticNonParty1

[SongSlideTextCat]
Inherits = SongRouletteTextCat

[SongSlideStatic1]
Inherits = DefaultBar1
Z = 0.4

[SongSlideStatic2]
Inherits = DefaultBar2
Z = 0.951

[SongSlideCover]
Inherits = SongRouletteCover
Padding = 120
Reflections = 1
ReflectionSpacing = 10

[SongSlideEqualizer]
Inherits = SongRouletteEqualizer

[SongSlideMedleyIcon]
X = 335
Y = 445
W = 24
H = 24
Z = 1
Color = White
Tex = icon_song_medley
Type = Transparent
Reflection = 1
ReflectionSpacing = 22

[SongSlideCalculatedMedleyIcon]
Inherits = SongSlideMedleyIcon
Tex = icon_song_calcmedley

[SongSlideVideoIcon]
Inherits = SongSlideMedleyIcon
X = 310
Tex = icon_song_video

[SongSlideDuetIcon]
Inherits = SongSlideMedleyIcon
Tex = icon_song_duet

[SongSlideRapIcon]
Inherits = SongSlideMedleyIcon
Tex = icon_song_rap

[SongSlideRapToFreestyleIcon]
Inherits = SongSlideMedleyIcon
Tex = icon_song_rap_to_freestyle

[SongSlideStatic3]
X = 278
Y = 120
W = 244
H = 200
Z = 1
Color = ColorLight
Tex = SongSelection1
Type = Colorized

[SongSlideStatic4]
X = 300
Y = 320
W = 200
H = 160
Z = 1
Color = ColorLight
Tex = SongSelection2
Type = Colorized
Reflection = 1
ReflectionSpacing = 2

[SongSlideTextArtist]
Inherits = SongRouletteTextArtist

[SongSlideTextTitle]
Inherits = SongRouletteTextTitle

[SongSlideTextNumber]
Inherits = SongRouletteTextNumber

[SongSlideTextYear]
Inherits = SongRouletteTextYear

[SongSlideTextScore]
Inherits = SongRouletteTextScore

[SongSlideTextMaxScore]
Inherits = SongRouletteTextMaxScore

[SongSlideTextMediaScore]
Inherits = SongRouletteTextMediaScore

[SongSlideTextMaxScore2]
Inherits = SongRouletteTextMaxScore2

[SongSlideTextMediaScore2]
Inherits = SongRouletteTextMediaScore2

[SongSlideTextScoreUser]
Inherits = SongRouletteTextScoreUser

[SongSlideTextMaxScoreLocal]
Inherits = SongRouletteTextMaxScoreLocal

[SongSlideTextMediaScoreLocal]
Inherits = SongRouletteTextMediaScoreLocal

[SongSlideTextScoreUserLocal]
Inherits = SongRouletteTextScoreUserLocal

[SongSlideTextNonParty1]
Inherits = SongRouletteTextNonParty1

[SongSlideStaticNonParty2]
Inherits = SongRouletteStaticNonParty2

[SongSlideTextNonParty2]
Inherits = SongRouletteTextNonParty2

[SongSlideStaticNonParty3]
Inherits = SongRouletteStaticNonParty3

[SongSlideTextNonParty3]
Inherits = SongRouletteTextNonParty3

[SongSlideStaticNonParty4]
Inherits = SongRouletteStaticNonParty4

[SongSlideTextNonParty4]
Inherits = SongRouletteTextNonParty4

[SongSlideStaticNonParty5]
Inherits = SongRouletteStaticNonParty5

[SongSlideTextNonParty5]
Inherits = SongRouletteTextNonParty5

[SongSlideStaticNonParty6]
Inherits = SongRouletteStaticNonParty6

[SongSlideTextNonParty6]
Inherits = SongRouletteTextNonParty6

[SongSlideStaticParty1]
Inherits = DefaultPartyIcon

[SongSlideStaticParty2]
Inherits = SongRouletteStaticParty2

[SongSlideTextParty3]
Inherits = DefaultLegendText
Z = 0.952
Text = SONG_MENU_NAME_PARTY_JOKER

[SongSlideStaticParty3]
Inherits = SongRouletteStaticParty3

[SongSlideTextParty4]
Inherits = SongRouletteTextParty4

[SongSlideStaticParty4]
Inherits = SongRouletteStaticParty4

[SongSlideTextParty5]
Inherits = SongRouletteTextParty5

[SongSlideTextParty1]
Inherits = DefaultPartyTitleText

[SongSlideTextParty2]
Inherits = DefaultTextWhereAmI
Text = PARTY_SONG_WHEREAMI

[SongSlideStaticTeam1Joker1]
Inherits = SongRouletteStaticTeam1Joker1

[SongSlideStaticTeam1Joker2]
Inherits = SongRouletteStaticTeam1Joker2

[SongSlideStaticTeam1Joker3]
Inherits = SongRouletteStaticTeam1Joker3

[SongSlideStaticTeam1Joker4]
Inherits = SongRouletteStaticTeam1Joker4

[SongSlideStaticTeam1Joker5]
Inherits = SongRouletteStaticTeam1Joker5

[SongSlideStaticTeam2Joker1]
Inherits = SongRouletteStaticTeam2Joker1

[SongSlideStaticTeam2Joker2]
Inherits = SongRouletteStaticTeam2Joker2

[SongSlideStaticTeam2Joker3]
Inherits = SongRouletteStaticTeam2Joker3

[SongSlideStaticTeam2Joker4]
Inherits = SongRouletteStaticTeam2Joker4

[SongSlideStaticTeam2Joker5]
Inherits = SongRouletteStaticTeam2Joker5

[SongSlideStaticTeam3Joker1]
Inherits = SongRouletteStaticTeam3Joker1

[SongSlideStaticTeam3Joker2]
Inherits = SongRouletteStaticTeam3Joker2

[SongSlideStaticTeam3Joker3]
Inherits = SongRouletteStaticTeam3Joker3

[SongSlideStaticTeam3Joker4]
Inherits = SongRouletteStaticTeam3Joker4

[SongSlideStaticTeam3Joker5]
Inherits = SongRouletteStaticTeam3Joker5

[SongSlideInfoMessageBG]
Inherits = SongRouletteInfoMessageBG

[SongSlideInfoMessageText]
Inherits = SongRouletteInfoMessageText

[SongSlideTextMedleyNumber1]
Inherits = SongRouletteTextMedleyNumber1

[SongSlideTextMedleyArtist1]
Inherits = SongRouletteTextMedleyArtist1

[SongSlideTextMedleyTitle1]
Inherits = SongRouletteTextMedleyTitle1

[SongSlideTextMedleyNumber2]
Inherits = SongRouletteTextMedleyNumber2

[SongSlideTextMedleyArtist2]
Inherits = SongRouletteTextMedleyArtist2

[SongSlideTextMedleyTitle2]
Inherits = SongRouletteTextMedleyTitle2

[SongSlideTextMedleyNumber3]
Inherits = SongRouletteTextMedleyNumber3

[SongSlideTextMedleyArtist3]
Inherits = SongRouletteTextMedleyArtist3

[SongSlideTextMedleyTitle3]
Inherits = SongRouletteTextMedleyTitle3

[SongSlideTextMedleyNumber4]
Inherits = SongRouletteTextMedleyNumber4

[SongSlideTextMedleyArtist4]
Inherits = SongRouletteTextMedleyArtist4

[SongSlideTextMedleyTitle4]
Inherits = SongRouletteTextMedleyTitle4

[SongSlideStaticMedley1]
Inherits = SongRouletteStaticMedley1
Z = 1

[SongSlideStaticMedley2]
Inherits = SongRouletteStaticMedley2
Z = 1

[SongSlideStaticMedley3]
Inherits = SongRouletteStaticMedley3
Z = 1

[SongSlideStaticMedley4]
Inherits = SongRouletteStaticMedley4
Z = 1

