########################################################################################
##### 																			   #####
#####                   			      List                                     #####
##### 																			   #####
########################################################################################

[SongListBackground]
Tex = SongBG

[SongListStaticNonParty1]
Inherits = SongRouletteStaticNonParty1

[SongListTextCat]
Inherits = SongRouletteTextCat

[SongListStatic1]
Inherits = DefaultBar1
Z = 0.4

[SongListStatic2]
Inherits = DefaultBar2
Z = 0.951

[SongListSelectSong]
X = 40
Y = 110
W = 460
H = 80
Z = 0.50
Rows = 5
Padding = 2
DColor = GrayLightest
Color = ColorLight
Tex = SongSelection5
DTex = SongSelection4
Type = Colorized
Reflection = 0
ReflectionSpacing = 0

[SongListCover]
X = 44
Y = 115
W = 75
H = 70
Z = 0.95
SelectX = 525
SelectY = 340
SelectW = 215
SelectH = 190
SelectReflection = 0
SelectReflectionSpacing = 0
Padding = 12
Reflections = 0
Rows = 5

[SongListEqualizer]
Visible = 1
Direction = 1
Color = White
Alpha = 1
X = 750
Y = 525
PieceW = 4
PieceH = 4
Space = 1
Bands = 7
Length = 15
Reflection = 0
ReflectionSpacing = 0

[SongListMedleyIcon]
X = 470
Y = 142
W = 22
H = 22
Z = 1
Color = White
Tex = icon_song_medley
Type = Transparent
Reflection = 0

[SongListCalculatedMedleyIcon]
Inherits = SongListMedleyIcon
Tex = icon_song_calcmedley

[SongListVideoIcon]
Inherits = SongListMedleyIcon
Y = 116
Tex = icon_song_video

[SongListDuetIcon]
Inherits = SongListMedleyIcon
Tex = icon_song_duet

[SongListRapIcon]
Inherits = SongListMedleyIcon
Tex = icon_song_rap

[SongListRapToFreestyleIcon]
Inherits = SongListMedleyIcon
Tex = icon_song_rap_to_freestyle

[SongListTextArtist]
X = 130
Y = 120
W = 440
Color = White
Font = 0
Style = 1
Size = 28
Align = 0
Text =

[SongListTextTitle]
Inherits = SongListTextArtist
Y = 150
W = 330
Style = 0
Size = 26

[SongListTextNumber]
X = 280
Y = 518
Z = 0.95
Color = White
Size = 14
Align = 1
Reflection = 1
ReflectionSpacing = 2

[SongListTextYear]
X = 490
Y = 168
Z = 0.95
Color = White
Size = 18
Align = 2

[SongListTextScore]
X = 525
Y = 235
Color = ColorLight
Font = 0
Style = 0
Size = 24
Align = 0

[SongListTextMaxScore]
X = 525
Y = 265
Color = White
Font = 0
Style = 0
Size = 22
Align = 0
Text =SONG_SCORE_MAX

[SongListTextMediaScore]
Inherits = SongListTextMaxScore
Y = 305
Text =SONG_SCORE_MEDIA

[SongListTextMaxScore2]
X = 665
Y = 265
Color = White
Font = 0
Style = 0
Size = 22
Align = 2

[SongListTextMediaScore2]
Inherits = SongListTextMaxScore2
Y = 305

[SongListTextScoreUser]
X = 665
Y = 283
Color = ColorLight
Font = 0
Style = 0
Size = 20
Align = 2

[SongListTextMaxScoreLocal]
X = 675
Y = 265
Color = White
Font = 0
Style = 0
Size = 22
Align = 0

[SongListTextMediaScoreLocal]
Inherits = SongListTextMaxScoreLocal
Y = 305

[SongListTextScoreUserLocal]
X = 675
Y = 283
Color = ColorLight
Font = 0
Style = 0
Size = 20
Align = 0

[SongListTextNonParty1]
Inherits = SongRouletteTextNonParty1

[SongListStaticNonParty2]
Inherits = SongRouletteStaticNonParty2

[SongListTextNonParty2]
Inherits = SongRouletteTextNonParty2

[SongListStaticNonParty3]
Inherits = SongRouletteStaticNonParty3

[SongListTextNonParty3]
Inherits = SongRouletteTextNonParty3

[SongListStaticNonParty4]
Inherits = SongRouletteStaticNonParty4

[SongListTextNonParty4]
Inherits = SongRouletteTextNonParty4

[SongListStaticNonParty5]
Inherits = SongRouletteStaticNonParty5

[SongListTextNonParty5]
Inherits = SongRouletteTextNonParty5

[SongListStaticNonParty6]
Inherits = SongRouletteStaticNonParty6

[SongListTextNonParty6]
Inherits = SongRouletteTextNonParty6

[SongListStaticParty1]
Inherits = DefaultPartyIcon

[SongListStaticParty2]
Inherits = SongRouletteStaticParty2

[SongListTextParty3]
Inherits = DefaultLegendText
Z = 0.952
Text = SONG_MENU_NAME_PARTY_JOKER

[SongListStaticParty3]
Inherits = SongRouletteStaticParty3

[SongListTextParty4]
Inherits = SongRouletteTextParty4

[SongListStaticParty4]
Inherits = SongRouletteStaticParty4

[SongListTextParty5]
Inherits = SongRouletteTextParty5

[SongListTextParty1]
Inherits = DefaultPartyTitleText

[SongListTextParty2]
Inherits = DefaultTextWhereAmI
Text = PARTY_SONG_WHEREAMI

[SongListStaticTeam1Joker1]
Inherits = SongRouletteStaticTeam1Joker1

[SongListStaticTeam1Joker2]
Inherits = SongRouletteStaticTeam1Joker2

[SongListStaticTeam1Joker3]
Inherits = SongRouletteStaticTeam1Joker3

[SongListStaticTeam1Joker4]
Inherits = SongRouletteStaticTeam1Joker4

[SongListStaticTeam1Joker5]
Inherits = SongRouletteStaticTeam1Joker5

[SongListStaticTeam2Joker1]
Inherits = SongRouletteStaticTeam2Joker1

[SongListStaticTeam2Joker2]
Inherits = SongRouletteStaticTeam2Joker2

[SongListStaticTeam2Joker3]
Inherits = SongRouletteStaticTeam2Joker3

[SongListStaticTeam2Joker4]
Inherits = SongRouletteStaticTeam2Joker4

[SongListStaticTeam2Joker5]
Inherits = SongRouletteStaticTeam2Joker5

[SongListStaticTeam3Joker1]
Inherits = SongRouletteStaticTeam3Joker1

[SongListStaticTeam3Joker2]
Inherits = SongRouletteStaticTeam3Joker2

[SongListStaticTeam3Joker3]
Inherits = SongRouletteStaticTeam3Joker3

[SongListStaticTeam3Joker4]
Inherits = SongRouletteStaticTeam3Joker4

[SongListStaticTeam3Joker5]
Inherits = SongRouletteStaticTeam3Joker5

[SongListInfoMessageBG]
Inherits = SongRouletteInfoMessageBG

[SongListInfoMessageText]
Inherits = SongRouletteInfoMessageText

[SongListTextMedleyMax]
N = 3

[SongListTextMedleyNumber1]
X=540
Y=100 
Color=White
Font=1
Size=20
Align=1

[SongListTextMedleyArtist1]
X=565
Y=91
Color=ColorDark
Font=0
Size=20
Align=0

[SongListTextMedleyTitle1]
X=565
Y=108
Color=White
Font=0
Size=20
Align=0

[SongListTextMedleyNumber2]
Inherits = SongListTextMedleyNumber1
Y=145

[SongListTextMedleyArtist2]
Inherits = SongListTextMedleyArtist1
Y=136

[SongListTextMedleyTitle2]
Inherits = SongListTextMedleyTitle1
Y=153

[SongListTextMedleyNumber3]
Inherits = SongListTextMedleyNumber1
Y=190

[SongListTextMedleyArtist3]
Inherits = SongListTextMedleyArtist1
Y=181

[SongListTextMedleyTitle3]
Inherits = SongListTextMedleyTitle1
Y=198

[SongListStaticMedley1]
Tex = PlayerNumberBox
X = 525
Y = 95
W = 30
H = 30
Color = ColorDark
Type = Colorized

[SongListStaticMedley2]
Inherits = SongListStaticMedley1
Y = 140

[SongListStaticMedley3]
Inherits = SongListStaticMedley1
Y = 185

