########################################################################################
##### 																			   #####
#####                   		   	     Mosaic                                    #####
##### 																			   #####
########################################################################################

[SongMosaicBackground]
Tex = SongBG

[SongMosaicStaticNonParty1]
Inherits = SongRouletteStaticNonParty1

[SongMosaicTextCat]
Inherits = SongRouletteTextCat

[SongMosaicStatic1]
Inherits = DefaultBar1
Z = 0.4

[SongMosaicStatic2]
Inherits = DefaultBar2
Z = 0.951

[SongMosaicCover]
X = 70
Y = 110
W = 135
H = 135
SelectX = 215
SelectY = 110
SelectW = 305
SelectH = 305
ZoomThumbW = 140
ZoomThumbH = 140
ZoomThumbStyle = 0
Rows = 3
Cols = 1
Padding = 4
Reflections = 0

[SongMosaicEqualizer]
Visible = 1
Direction = 1
Color = White
Alpha = 1
X = 40
Y = 516
PieceW = 5
PieceH = 5
Space = 1
Bands = 4  
Length = 18
Reflection = 1
ReflectionSpacing = 2

[SongMosaicMedleyIcon]
X = 462
Y = 492
W = 24
H = 24
Z = 1
Color = White
Tex = icon_song_medley
Type = Transparent
Reflection = 0
ReflectionSpacing = 0

[SongMosaicCalculatedMedleyIcon]
Inherits = SongMosaicMedleyIcon
Tex = icon_song_calcmedley

[SongMosaicVideoIcon]
Inherits = SongMosaicMedleyIcon
X = 490
Tex = icon_song_video

[SongMosaicDuetIcon]
Inherits = SongMosaicMedleyIcon
Tex = icon_song_duet

[SongMosaicRapIcon]
Inherits = SongMosaicMedleyIcon
Tex = icon_song_rap

[SongMosaicRapToFreestyleIcon]
Inherits = SongMosaicMedleyIcon
Tex = icon_song_rap_to_freestyle

[SongMosaicStatic3]
X = 215
Y = 415
W = 305
H = 107
Z = 0.9
Color = ColorLight
Tex = JukeboxSongListBackground
Type = Colorized
Reflection = 1
ReflectionSpacing = 2

[SongMosaicTextArtist]
X = 223
Y = 425
W = 300
Color = White
Font = 0
Style = 1
Size = 28
Align = 0
Text =

[SongMosaicTextTitle]
Inherits = SongMosaicTextArtist
Y = 475
Style = 0
Size = 24

[SongMosaicTextNumber]
X = 140
Y = 526
Z = 0.95
Color = White
Size = 14
Align = 1
Reflection = 0
ReflectionSpacing = 0

[SongMosaicTextYear]
X = 455
Y = 500
Z = 1
Color = White
Size = 18
Align = 2

[SongMosaicTextScore]
Inherits = SongRouletteTextScore

[SongMosaicTextMaxScore]
Inherits = SongRouletteTextMaxScore

[SongMosaicTextMediaScore]
Inherits = SongRouletteTextMediaScore

[SongMosaicTextMaxScore2]
Inherits = SongRouletteTextMaxScore2

[SongMosaicTextMediaScore2]
Inherits = SongRouletteTextMediaScore2

[SongMosaicTextScoreUser]
Inherits = SongRouletteTextScoreUser

[SongMosaicTextMaxScoreLocal]
Inherits = SongRouletteTextMaxScoreLocal

[SongMosaicTextMediaScoreLocal]
Inherits = SongRouletteTextMediaScoreLocal

[SongMosaicTextScoreUserLocal]
Inherits = SongRouletteTextScoreUserLocal

[SongMosaicTextNonParty1]
Inherits = SongRouletteTextNonParty1

[SongMosaicStaticNonParty2]
Inherits = SongRouletteStaticNonParty2

[SongMosaicTextNonParty2]
Inherits = DefaultLegendText
Inherits = SongRouletteTextNonParty2

[SongMosaicStaticNonParty3]
Inherits = SongRouletteStaticNonParty3

[SongMosaicTextNonParty3]
Inherits = SongRouletteTextNonParty3

[SongMosaicStaticNonParty4]
Inherits = SongRouletteStaticNonParty4

[SongMosaicTextNonParty4]
Inherits = SongRouletteTextNonParty4

[SongMosaicStaticNonParty5]
Inherits = SongRouletteStaticNonParty5

[SongMosaicTextNonParty5]
Inherits = SongRouletteTextNonParty5

[SongMosaicStaticNonParty6]
Inherits = SongRouletteStaticNonParty6

[SongMosaicTextNonParty6]
Inherits = SongRouletteTextNonParty6

[SongMosaicStaticParty1]
Inherits = DefaultPartyIcon

[SongMosaicStaticParty2]
Inherits = SongRouletteStaticParty2

[SongMosaicTextParty3]
Inherits = DefaultLegendText
Z = 0.952
Text = SONG_MENU_NAME_PARTY_JOKER

[SongMosaicStaticParty3]
Inherits = SongRouletteStaticParty3

[SongMosaicTextParty4]
Inherits = SongRouletteTextParty4

[SongMosaicStaticParty4]
Inherits = SongRouletteStaticParty4

[SongMosaicTextParty5]
Inherits = SongRouletteTextParty5

[SongMosaicTextParty1]
Inherits = DefaultPartyTitleText

[SongMosaicTextParty2]
Inherits = DefaultTextWhereAmI
Text = PARTY_SONG_WHEREAMI

[SongMosaicStaticTeam1Joker1]
Inherits = SongRouletteStaticTeam1Joker1

[SongMosaicStaticTeam1Joker2]
Inherits = SongRouletteStaticTeam1Joker2

[SongMosaicStaticTeam1Joker3]
Inherits = SongRouletteStaticTeam1Joker3

[SongMosaicStaticTeam1Joker4]
Inherits = SongRouletteStaticTeam1Joker4

[SongMosaicStaticTeam1Joker5]
Inherits = SongRouletteStaticTeam1Joker5

[SongMosaicStaticTeam2Joker1]
Inherits = SongRouletteStaticTeam2Joker1

[SongMosaicStaticTeam2Joker2]
Inherits = SongRouletteStaticTeam2Joker2

[SongMosaicStaticTeam2Joker3]
Inherits = SongRouletteStaticTeam2Joker3

[SongMosaicStaticTeam2Joker4]
Inherits = SongRouletteStaticTeam2Joker4

[SongMosaicStaticTeam2Joker5]
Inherits = SongRouletteStaticTeam2Joker5

[SongMosaicStaticTeam3Joker1]
Inherits = SongRouletteStaticTeam3Joker1

[SongMosaicStaticTeam3Joker2]
Inherits = SongRouletteStaticTeam3Joker2

[SongMosaicStaticTeam3Joker3]
Inherits = SongRouletteStaticTeam3Joker3

[SongMosaicStaticTeam3Joker4]
Inherits = SongRouletteStaticTeam3Joker4

[SongMosaicStaticTeam3Joker5]
Inherits = SongRouletteStaticTeam3Joker5

[SongMosaicInfoMessageBG]
Inherits = SongRouletteInfoMessageBG

[SongMosaicInfoMessageText]
Inherits = SongRouletteInfoMessageText

[SongMosaicTextMedleyMax]
N = 7

[SongMosaicTextMedleyNumber1]
X=545
Y=116 
Color=White
Font=1
Size=20
Align=1

[SongMosaicTextMedleyNumber2]
Inherits = SongMosaicTextMedleyNumber1
Y=161

[SongMosaicTextMedleyNumber3]
Inherits = SongMosaicTextMedleyNumber1
Y=206

[SongMosaicTextMedleyNumber4]
Inherits = SongMosaicTextMedleyNumber1
Y=251

[SongMosaicTextMedleyNumber5]
Inherits = SongMosaicTextMedleyNumber1
Y=296

[SongMosaicTextMedleyNumber6]
Inherits = SongMosaicTextMedleyNumber1
Y=341

[SongMosaicTextMedleyNumber7]
Inherits = SongMosaicTextMedleyNumber1
Y=386

[SongMosaicTextMedleyArtist1]
X=570
Y=107
Color=ColorDark
Font=0
Size=20
Align=0

[SongMosaicTextMedleyArtist2]
Inherits = SongMosaicTextMedleyArtist1
Y=152

[SongMosaicTextMedleyArtist3]
Inherits = SongMosaicTextMedleyArtist1
Y=197

[SongMosaicTextMedleyArtist4]
Inherits = SongMosaicTextMedleyArtist1
Y=242

[SongMosaicTextMedleyArtist5]
Inherits = SongMosaicTextMedleyArtist1
Y=287

[SongMosaicTextMedleyArtist6]
Inherits = SongMosaicTextMedleyArtist1
Y=332

[SongMosaicTextMedleyArtist7]
Inherits = SongMosaicTextMedleyArtist1
Y=377

[SongMosaicTextMedleyTitle1]
X=570
Y=123
Color=White
Font=0
Size=20
Align=0

[SongMosaicTextMedleyTitle2]
Inherits = SongMosaicTextMedleyTitle1
Y=168

[SongMosaicTextMedleyTitle3]
Inherits = SongMosaicTextMedleyTitle1
Y=213

[SongMosaicTextMedleyTitle4]
Inherits = SongMosaicTextMedleyTitle1
Y=257

[SongMosaicTextMedleyTitle5]
Inherits = SongMosaicTextMedleyTitle1
Y=302

[SongMosaicTextMedleyTitle6]
Inherits = SongMosaicTextMedleyTitle1
Y=347

[SongMosaicTextMedleyTitle7]
Inherits = SongMosaicTextMedleyTitle1
Y=392

[SongMosaicStaticMedley1]
Tex = PlayerNumberBox
X = 530
Y = 110
W = 30
H = 30
Color = ColorDark
Type = Colorized

[SongMosaicStaticMedley2]
Inherits = SongMosaicStaticMedley1
Y = 155

[SongMosaicStaticMedley3]
Inherits = SongMosaicStaticMedley1
Y = 200

[SongMosaicStaticMedley4]
Inherits = SongMosaicStaticMedley1
Y = 245

[SongMosaicStaticMedley5]
Inherits = SongMosaicStaticMedley1
Y = 290

[SongMosaicStaticMedley6]
Inherits = SongMosaicStaticMedley1
Y = 335

[SongMosaicStaticMedley7]
Inherits = SongMosaicStaticMedley1
Y = 380

