## Oscilloscope Position Screen  ##

# O N E  P L A Y E R  M O D E # # # # # # # # # # # # # # # # # # # #
#PlayerOne
[SingP1Oscilloscope]
X = 80
Y = 275
H = 30
W = 100

# T W O  P L A Y E R  M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1TwoPOscilloscope]
X = 80
Y = 95
H = 30
W = 100

#Player Two
[SingP2ROscilloscope]
Inherits = SingP1TwoPOscilloscope
Y = 275

# T H R E E  P L A Y E R  M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1ThreePOscilloscope]
X = 15
Y = 15
H = 30
W = 160

#Player Two
[SingP2MOscilloscope]
Inherits = SingP1ThreePOscilloscope
X = 310

#Player Three
[SingP3ROscilloscope]
Inherits = SingP1ThreePOscilloscope
X = 610

# T H R E E  P L A Y E R  D U E T  M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingDuetP1ThreePOscilloscope]
X = 56
Y = 98
H = 25
W = 100

#Player Two
[SingDuetP2MOscilloscope]
Inherits = SingDuetP1ThreePOscilloscope
Y = 222

#Player Three
[SingDuetP3ROscilloscope]
Inherits = SingDuetP1ThreePOscilloscope
Y = 347

## 4/6 Players One Screen  ##

# FOUR  P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1FourPOscilloscope]
X = 22
Y = 25
H = 30
W = 157

#Player Two
[SingP2FourPOscilloscope]
Inherits = SingP1FourPOscilloscope
X = 222

#Player Three
[SingP3FourPOscilloscope]
Inherits = SingP1FourPOscilloscope
X = 422

#Player Four
[SingP4FourPOscilloscope]
Inherits = SingP1FourPOscilloscope
X = 622

# SIX  P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1SixPOscilloscope]
X = 20
Y = 8
H = 30
W = 100

#Player Two
[SingP2SixPOscilloscope]
Inherits = SingP1SixPOscilloscope
X = 150

#Player Three
[SingP3SixPOscilloscope]
Inherits = SingP1SixPOscilloscope
X = 280

#Player Four
[SingP4SixPOscilloscope]
Inherits = SingP1SixPOscilloscope
X = 410

#Player Five
[SingP5SixPOscilloscope]
Inherits = SingP1SixPOscilloscope
X = 540

#Player Six
[SingP6SixPOscilloscope]
Inherits = SingP1SixPOscilloscope
X = 670

# FOUR DUET P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1DuetFourPOscilloscope]
X = 60
Y = 118
H = 25
W = 100

#Player Two
[SingP2DuetFourPOscilloscope]
Inherits = SingP1DuetFourPOscilloscope
Y = 298

#Player Three
[SingP3DuetFourPOscilloscope]
Inherits = SingP1DuetFourPOscilloscope
X = 430

#Player Four
[SingP4DuetFourPOscilloscope]
Inherits = SingP3DuetFourPOscilloscope
Y = 298

# SIX  DUET P L A Y E R   M O D E # # # # # # # # # # # # # # # # # # # #
#Player One
[SingP1DuetSixPOscilloscope]
X = 60
Y = 107
H = 25
W = 100

#Player Two
[SingP2DuetSixPOscilloscope]
Inherits = SingP1DuetSixPOscilloscope
Y = 236

#Player Three
[SingP3DuetSixPOscilloscope]
Inherits = SingP1DuetSixPOscilloscope
Y = 362

#Player Four
[SingP4DuetSixPOscilloscope]
Inherits = SingP1DuetSixPOscilloscope
X = 430

#Player Five
[SingP5DuetSixPOscilloscope]
Inherits = SingP4DuetSixPOscilloscope
Y = 236

#Player Six
[SingP6DuetSixPOscilloscope]
Inherits = SingP4DuetSixPOscilloscope
Y = 362

