[AboutMainBackground]
Tex = MainBG

[AboutMainButtonCredits]
X = 589
Y = 415
W = 190
H = 50
Tex = Button
DColor = ColorDark
Color = ColorLight
Type = Transparent
Texts = 1
Reflection = 0

[AboutMainButtonCreditsText1]
X = 95
Y = 10
Font = 0
Style = 0
Size = 30
Align = 1
Text = ABOUT_USDX_CREDITS
Color = White

[AboutMainButtonExit]
Inherits = AboutMainButtonCredits
Y = 480

[AboutMainButtonExitText1]
Inherits = AboutMainButtonCreditsText1
Text = SING_OPTIONS_EXIT

[AboutMainTextOverview]
X = 45
Y = 125
W = 510
Color = White
Font = 0
Style = 0
Size = 24
Align = 0
Text =

[AboutMainStatic1]
X = 40
Y = 22
W = 27
H = 27
Color = White
Tex = MainIcon
Type = Colorized

[AboutMainStatic2]
Inherits = DefaultBar1

[AboutMainStatic3]
Inherits = DefaultBar2

[AboutMainStatic4]
Inherits = DefaultLegendStatic
Tex = ButtonNavi

[AboutMainStatic5]
Inherits = DefaultLegendStatic
X = 388
Tex = ButtonEsc

[AboutMainStatic6]
X = 40
Y = 100
W = 520
H = 20
Tex = StatMainBG1
Color = ColorLight
Type = Colorized

[AboutMainStatic7]
X = 40
Y = 120
W = 520
H = 370
Tex = StatMainBG2
Color = ColorDark
Type = Colorized

[AboutMainStatic8]
X = 40
Y = 490
W = 520
H = 20
Tex = StatMainBG3
Color = ColorLight
Type = Colorized

[AboutMainText1]
X = 70
Y = 5
Color = White
Font = 0
Style = 0
Size = 60
Text = ABOUT_MAIN
Align = 0

[AboutMainText2]
Inherits = DefaultTextWhereAmI
Text = ABOUT_MAIN_WHEREAMI

[AboutMainText3]
X = 70
Y = 60
Color = White
Font = 0
Style = 0
Size = 30
Align = 0
Text = ABOUT_MAIN_DESC

[AboutMainText4]
Inherits = DefaultLegendText
Text = SING_LEGEND_NAVIGATE

[AboutMainText5]
Inherits = DefaultLegendText
X = 428
Text = SING_LEGEND_ESC

####### HelpPopup ########
[HelpPopupButton1]
X = 350
Y = 540
W = 100
H = 25
Tex = Rectangle
Color = Gray
DColor = GrayPopup
Type = Font Black
Z = 1
Texts = 1

[HelpPopupButton1Text1]
X = 50
Y = 0
Color = White
Font = 0
Style = 0
Size = 8
Text = OK
Align = 1
Z = 1

[HelpPopupSelectVolAudio]
Text = HELP_VOLUME_AUDIO
Tex = Rectangle
Type = Colorized
TexSBG = Rectangle
TypeSBG = Colorized
ShowArrows = 0
OneItemOnly = 1
X = 140
Y = 26
W = 260
H = 28
Z = 1
SkipX = -260
SBGW = 260
TextSize = 24
Color = Gray
DColor = GrayPopup
TColor = White
TDColor = GrayLight
SBGColor = GrayLight
SBGDColor = Gray
STColor = White
STDColor = GrayLightest

[HelpPopupSelectVolVocals]
Text = HELP_VOLUME_VOCALS
Tex = Rectangle
Type = Colorized
TexSBG = Rectangle
TypeSBG = Colorized
ShowArrows = 0
OneItemOnly = 1
X = 450
Y = 26
W = 260
H = 28
Z = 1
SkipX = -260
SBGW = 260
TextSize = 24
Color = Gray
DColor = GrayPopup
TColor = White
TDColor = GrayLight
SBGColor = GrayLight
SBGDColor = Gray
STColor = White
STDColor = GrayLightest

[HelpPopupSelectVolSfx]
Text = HELP_VOLUME_SFX
Tex = Rectangle
Type = Colorized
TexSBG = Rectangle
TypeSBG = Colorized
ShowArrows = 0
OneItemOnly = 1
X = 140
Y = 58
W = 260
H = 28
Z = 1
SkipX = -260
SBGW = 260
TextSize = 24
Color = Gray
DColor = GrayPopup
TColor = White
TDColor = GrayLight
SBGColor = GrayLight
SBGDColor = Gray
STColor = White
STDColor = GrayLightest

[HelpPopupSelectVolPreview]
Text = HELP_VOLUME_PREVIEW
Tex = Rectangle
Type = Colorized
TexSBG = Rectangle
TypeSBG = Colorized
ShowArrows = 0
OneItemOnly = 1
X = 450
Y = 58
W = 260
H = 28
Z = 1
SkipX = -260
SBGW = 260
TextSize = 24
Color = Gray
DColor = GrayPopup
TColor = White
TDColor = GrayLight
SBGColor = GrayLight
SBGDColor = Gray
STColor = White
STDColor = GrayLightest

[HelpPopupSelectVolAudio]
Text = HELP_VOLUME_AUDIO
Tex = Rectangle
Type = Colorized
TexSBG = Rectangle
TypeSBG = Colorized
ShowArrows = 0
OneItemOnly = 1
X = 140
Y = 26
W = 260
H = 28
Z = 1
SkipX = -260
SBGW = 260
TextSize = 24
Color = Gray
DColor = GrayPopup
TColor = White
TDColor = GrayLight
SBGColor = GrayLight
SBGDColor = Gray
STColor = White
STDColor = GrayLightest

[HelpPopupSelectVolVocals]
Text = HELP_VOLUME_VOCALS
Tex = Rectangle
Type = Colorized
TexSBG = Rectangle
TypeSBG = Colorized
ShowArrows = 0
OneItemOnly = 1
X = 450
Y = 26
W = 260
H = 28
Z = 1
SkipX = -260
SBGW = 260
TextSize = 24
Color = Gray
DColor = GrayPopup
TColor = White
TDColor = GrayLight
SBGColor = GrayLight
SBGDColor = Gray
STColor = White
STDColor = GrayLightest

[HelpPopupSelectVolSfx]
Text = HELP_VOLUME_SFX
Tex = Rectangle
Type = Colorized
TexSBG = Rectangle
TypeSBG = Colorized
ShowArrows = 0
OneItemOnly = 1
X = 140
Y = 58
W = 260
H = 28
Z = 1
SkipX = -260
SBGW = 260
TextSize = 24
Color = Gray
DColor = GrayPopup
TColor = White
TDColor = GrayLight
SBGColor = GrayLight
SBGDColor = Gray
STColor = White
STDColor = GrayLightest

[HelpPopupSelectVolPreview]
Text = HELP_VOLUME_PREVIEW
Tex = Rectangle
Type = Colorized
TexSBG = Rectangle
TypeSBG = Colorized
ShowArrows = 0
OneItemOnly = 1
X = 450
Y = 58
W = 260
H = 28
Z = 1
SkipX = -260
SBGW = 260
TextSize = 24
Color = Gray
DColor = GrayPopup
TColor = White
TDColor = GrayLight
SBGColor = GrayLight
SBGDColor = Gray
STColor = White
STDColor = GrayLightest
