; disabled to create a more compact layout
[ScoreText1]
Enabled = 0

; disabled to create a more compact layout
[ScoreTextArtistTitle]
Enabled = 0

; add the title as a separate element
[ScoreTextTitle]
X = 70
Y = 10
Color = White
Font = 0
Style = 0
Size = 32
Text = Title

; add the artist as a separate element
[ScoreTextArtist]
X = 70
Y = 36
Color = White
Font = 0
Style = 0
Size = 24
Text = Artist

[ScoreStatic1]
Inherits = DefaultIcon
;Type = Colorized
Type = Transparent

