# the placement of the buttons is modified
# ie "Send Score x Player"
# Everything from "Send Score PopUp" onwards is unmodified

############################
#    Send Score 1 Player   #
############################

[ScoreButtonSend1]
X = 70
Y = 61
W = 180
H = 25
Z = 1
Tex = ButtonSendScore
DColor = ColorLight
Color = ColorDark
Type = Transparent
Texts = 1

;this is relative to within the button
[ScoreButtonSend1Text1]
X = 90
Y = 2
Font = 0
Style = 0
Size = 21
Align = 1
Color = White
Text = SCORE_SEND_DESC

############################
#  Send Score 2/4 Players  #
############################

[ScoreButtonSend2]
Inherits = ScoreButtonSend1

;this is relative to within the button
[ScoreButtonSend2Text1]
Inherits = ScoreButtonSend1Text1

############################
#  Send Score 3/6 Players  #
############################

[ScoreButtonSend3]
Inherits = ScoreButtonSend1

;this is relative to within the button
[ScoreButtonSend3Text1]
Inherits = ScoreButtonSend1Text1
