##################################
##########     Duet     ##########
##################################

[SingLyricsDuetP2UpperBar]
X = 80
W = 640
Y = 513
H = 41
;YOffSet (+/-) for the Sing-Indicator
IndicatorYOffset = 3

[SingLyricsDuetP2LowerBar]
Inherits = SingLyricsDuetP2UpperBar
Y = 553

;Y=2+60
[SingLyricsDuetP1UpperBar]
X = 80
W = 640
Y = 62
H = 41
;YOffSet (+/-) for the Sing-Indicator
IndicatorYOffset = 3

;Y=42+60
[SingLyricsDuetP1LowerBar]
Inherits = SingLyricsDuetP1UpperBar
Y = 102

;Y=0+60
[SingLyricsBarDuet]
Inherits = SingLyricsBar
Tex = LyricBarDuet
Y = 60
