########################################################################################
##### 																			   #####
#####                   			   Chessboard                                  #####
##### 																			   #####
########################################################################################

[SongChessboardStaticNonParty1]
Inherits = SongRouletteStaticNonParty1
;Type = Colorized
Type = Transparent

[SongChessboardCover]
; X = 270
X = 250
Y = 100
; W = 100
W = 77
H = 100
SelectX = 25
;SelectY = 120
SelectY = 100
;SelectW = 154
SelectW = 200
;SelectH = 200
SelectH = 260
ZoomThumbW = 77
ZoomThumbH = 100
ZoomThumbStyle = 0
Rows = 3
Cols = 7
Padding = 2
Reflections = 0
Tex = PlayerNumberBox

[SongChessboardTextSpoiler]
X = 28
; Y = 120
Y = 100
W = 192
Color = White
Font = 0
Style = 0
Size = 20
Align = 0
Text =

[SongChessboardSpoilerBackground]
X = 25
; Y = 120
Y = 100
W = 200
H = 24
Tex = ScoreLine
Color = Black
Alpha = 1
Z = 0.99

[SongChessboardMedleyIcon]
X = 60
;Y = 445
Y = 485
W = 24
H = 24
Z = 0.95
Color = White
Tex = icon_song_medley
Type = Transparent
Reflection = 1
ReflectionSpacing = 22

[SongChessboardCalculatedMedleyIcon]
Inherits = SongChessboardMedleyIcon
Tex = icon_song_calc_medley

[SongChessboardVideoIcon]
Inherits = SongChessboardMedleyIcon
X = 35
Tex = icon_song_video

[SongChessboardDuetIcon]
Inherits = SongChessboardMedleyIcon
Tex = icon_song_duet

[SongChessboardRapIcon]
Inherits = SongChessboardMedleyIcon
Tex = icon_song_rap

[SongChessboardRapToFreestyleIcon]
Inherits = SongChessboardMedleyIcon
Tex = icon_song_rap_to_freestyle

[SongChessboardStatic3]
X = 25
;Y = 320
Y = 360
W = 200
H = 160
Z = 0.95
Color = ColorLight
Tex = SongSelection2
Type = Colorized
Reflection = 1
ReflectionSpacing = 2

[SongChessboardTextArtist]
X = 125
;Y = 328
Y = 368
W = 190
Color = White
Font = 0
Style = 1
Size = 24
Align = 1
Text =

[SongChessboardTextTitle]
Inherits = SongChessboardTextArtist
;Y = 394
Y = 434
Style = 0

[SongChessboardTextNumber]
X = 217
;Y = 457
Y = 497
Z = 0.95
Color = White
Size = 14
Align = 2
Reflection = 1
ReflectionSpacing = 21

[SongChessboardTextYear]
X = 125
;Y = 447
Y = 487
Z = 0.95
Color = White
Size = 20
Align = 1

; show [R]andom instead of [P]laylist
[SongChessboardStaticNonParty6]
Inherits = SongRouletteStaticNonParty6
;Tex = ButtonP
Tex = ButtonR

[SongChessboardTextNonParty6]
Inherits = SongRouletteTextNonParty6
;Text = SING_SONG_SELECTION_PLAYLIST
Text = JUKEBOX_RANDOM
